"use strict";
let H0=2463534242,GF=()=>{let x=H0;x^=x<<13;x^=x>>>17;x^=x<<5;H0=x;return x;},D=f=>function(){return f(this);},E=f=>function(p1){return f(this,p1);},L=f=>function(p1,p2){return f(this,p1,p2);},S=f=>function(p1,p2,p3){return f(this,p1,p2,p3,p3);},JL=f=>function(p1,p2,p3,p4){return f(this,p1,p2,p3,p4);},X=target=>target.$clinit=()=>{},M8=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}
else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},G=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=B1();}return function(){superclass.call(this);};},BW=cls=>Dk(cls),B1=()=>F,Cz=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},M$=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BY=(name,binaryName)=>{let cls=M$();cls.$meta.primitive
=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Gb=BY("char","C"),Ie=BY("byte","B"),Cn=BY("int","I"),EY=BY("long","J"),KK=BY("float","F"),K3=BY("void","V"),HD=new ArrayBuffer(16),JQ=new Float32Array(HD),Jd=new Int32Array(HD);
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let Jw=n=>{JQ[0]=n;return Jd[0];},E3=(a,b)=>a>b?1:a<b? -1:a===b?0:1,V=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Be=(a,b)=>(a>>>0)/(b>>>0)>>>0,M_=(a,b)=>(a>>>0)%(b>>>0)>>>0,Br=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},Nd=BigInt(0),Df=(lo,hi)=>BigInt.asIntN(64,BigInt.asUintN(64,BigInt(lo))|BigInt.asUintN(64,BigInt(hi)<<BigInt(32))),Bg
=val=>BigInt.asIntN(64,BigInt(val|0)),Ev=val=>Number(BigInt.asIntN(32,val))|0,Im=(a,b)=>a===b,Ju=(a,b)=>{a=BigInt.asUintN(64,a);b=BigInt.asUintN(64,b);return a<b? -1:a>b?1:0;},JA=(a,b)=>BigInt.asIntN(64,a*b),CL=(a,b)=>BigInt.asIntN(64,a&b),J1=(a,b)=>BigInt.asIntN(64,BigInt.asUintN(64,a)>>BigInt(b&63)),Bd=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bx(cls))(data);},KB=(cls,sz)=>new (Bx(cls))(new Array(sz)),DR;
if(typeof BigInt64Array!=='function'){DR=init=>new Fe(init);}else {DR=data=>{let buffer=new BigInt64Array(data.length);buffer.set(data);return new Fe(buffer);};}let Bt=sz=>new GW(new Uint16Array(sz)),Bf=sz=>new LF(new Int8Array(sz)),U=sz=>new G3(new Int32Array(sz)),GA=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new G3(buffer);},Bx=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(B1()).call(this);this.data=data;}JavaArray.prototype=Object.create((B1()).prototype);JavaArray.prototype.type
=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.cn=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bx(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta
={item:cls,supertypes:[B1()],primitive:false,superclass:B1(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},M9=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if(first>0){for(let i=0;i<first;i=i+1|0){cls=Bx(cls);}if(first===dimensions.length -1){return Bd(cls,dimensions[first]);}}let arrays=new Array(F4(dimensions,
first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bd(cls,firstDim);}return Ff(cls,arrays,dimensions,first);},D3=dimensions=>{let arrays=new Array(F4(dimensions,0));if(arrays.length===0){return M9(Cn,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=U(firstDim);}return Ff(Cn,arrays,dimensions,0);},F4=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===
0){break;}}return val;},Ff=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=Bx(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=KB(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit=packedIndex;}return arrays[0];},DJ,I0=strings=>{L4();DJ=new Array(strings.length);for(let i=0;i<strings.length;++i){DJ[i]=EO(BG(strings[i]));}},I=index=>
DJ[index],Dm=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Iy=array=>Dm(array,0,array.length),K8=string=>{let array=new Uint16Array(string.length);for(let i=0;i<array.length;++i){array[i]=string.charCodeAt(i);}return new GW(array);},BG=str=>str===null?null:Lo(str),Cf=str=>str===null?null:str.fp,L4=()=>BU(),EO;
{EO=str=>str;}let Jm=(obj,cls)=>obj instanceof B1()&&!!obj.constructor.$meta&&CN(obj.constructor,cls),CN=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&CN(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(CN(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},H=ex=>{throw Jk(ex);},Co=Symbol("javaException"),Jk=ex=>{let err=ex.$jsException;if(!err){let javaCause=Ni(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new BE("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Co]=ex;ex.$jsException=err;Hz(err,ex);}return err;},Hz
=(err,ex)=>{if(typeof IC==="function"&&err.stack){let stack=IC(err.stack);let javaStack=Bd(IW(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=LJ(BG(element.className),BG(element.methodName),BG(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Je(ex,javaStack);}}},BE;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");BE=function BE(message,cause){let self=Reflect.construct(Error,[void 0,cause],BE);Object.setPrototypeOf(self,BE.prototype);self[defaultMessage]=message;return self;}
;BE.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:BE},message:{get(){try {let javaException=this[Co];if(typeof javaException==='object'){let javaMessage=KS(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {BE=Error;}let BL=err=>{let ex=err[Co];if(!ex){ex=Le(BG("(JavaScript) "+err.toString()));err[Co]
=ex;ex.$jsException=err;Hz(err,ex);}return ex;},Le=message=>D7(message),KS=t=>H4(t),Ni=t=>Ia(t),IW=()=>NO,LJ=(className,methodName,fileName,lineNumber)=>{{return null;}},Je=(e,stack)=>{},ED=null,Jo=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}ED=packages;},CZ=data=>{let packages=ED;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className
=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject
=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods
!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function F(){this.$id$=0;}
let J=a=>{return;},NN=()=>{let a=new F();J(a);return a;},Cu=a=>{return Dk(a.constructor);},G2=a=>{let b,c;b=M5(EE(a));c=Q();K(K(c,I(0)),b);return P(c);},EE=a=>{let b;b=a;if(!b.$id$)b.$id$=GF();return a.$id$;},MZ=a=>{let b,c,d;if(!Jm(a,Cg)){b=a;if(b.constructor.$meta.item===null)H(Jq());}c=IS(a);b=c;d=GF();b.$id$=d;return c;};
function BB(){let a=this;F.call(a);a.gb=null;a.fX=null;a.fT=0;a.fY=0;}
let Di=a=>{a.fT=1;a.fY=1;a.h();},Ns=()=>{let a=new BB();Di(a);return a;},GZ=(a,b)=>{a.fT=1;a.fY=1;a.h();a.gb=b;},NG=a=>{let b=new BB();GZ(b,a);return b;},D4=(a,b,c)=>{a.fT=1;a.fY=1;a.h();a.gb=b;a.fX=c;},NI=(a,b)=>{let c=new BB();D4(c,a,b);return c;},FK=(a,b)=>{a.fT=1;a.fY=1;a.h();a.fX=b;},Ny=a=>{let b=new BB();FK(b,a);return b;},Jc=a=>{return a;},H4=a=>{return a.gb;},Ia=a=>{return a.fX===a?null:a.fX;},Ba=G(BB),Cd=a=>{Di(a);},Nn=()=>{let a=new Ba();Cd(a);return a;},Dj=(a,b,c)=>{D4(a,b,c);},Nt=(a,b)=>{let c=new Ba();Dj(c,
a,b);return c;},B5=(a,b)=>{GZ(a,b);},ND=a=>{let b=new Ba();B5(b,a);return b;},N=G(Ba),Y=a=>{Cd(a);},Nq=()=>{let a=new N();Y(a);return a;},Ha=(a,b,c)=>{Dj(a,b,c);},H7=(a,b)=>{let c=new N();Ha(c,a,b);return c;},Cb=(a,b)=>{B5(a,b);},D7=a=>{let b=new N();Cb(b,a);return b;},T=G(N),DQ=a=>{Y(a);},B$=()=>{let a=new T();DQ(a);return a;},W=(a,b)=>{Cb(a,b);},No=a=>{let b=new T();W(b,a);return b;},BO=G(0),BS=G(),GC=a=>{J(a);},Bz=G(0),GL=G(BS),J9=null,CO=()=>{CO=X(GL);Lw();},JZ=b=>{CO();if(isNaN(b)?1:0)return 2143289344;return Jw(b);},Lw
=()=>{J9=BW(KK);},KM=G(),FT=(b,c)=>{let d,e,f,g;d=b.data;e=Bt(c);f=Bm(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},F2=(b,c)=>{let d,e,f,g;d=b.data;e=Bf(c);f=Bm(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},BK=(b,c)=>{let d,e,f,g;d=b.data;e=U(c);f=Bm(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},LB=(b,c)=>{let d,e,f,g;d=b.data;e=L7(Cl(Cu(b)),c);f=Bm(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},I4=(b,c,d,e)=>{let f,g;if(c>d)H(BR());while(c<d){f
=b.data;g=c+1|0;f[c]=e;c=g;}},Go=(b,c)=>{I4(b,0,b.data.length,c);},JI=(b,c)=>{return K4(b,0,b.data.length,c);},K4=(b,c,d,e)=>{let f,g,h,i;if(c>d)H(BR());f=d-1|0;while(true){if(c>f)return ( -c|0)-1|0;g=b.data;h=(c+f|0)/2|0;i=g[h];if(i==e)break;if(e>=i)c=h+1|0;else f=h-1|0;}return h;},Cw=G(Ba),Dn=a=>{Cd(a);};
let NB=()=>{let a=new Cw();Dn(a);return a;},BJ=G(Cw),CG=a=>{Dn(a);},Nu=()=>{let a=new BJ();CG(a);return a;};
function HO(){BJ.call(this);this.g8=0;}
let F5=(a,b)=>{CG(a);a.g8=b;},Mf=a=>{let b=new HO();F5(b,a);return b;},Ln=G(),Nm=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c+f|0)<=Cx(b)){g=e+f|0;if(g<=Cx(d)){a:{b:{if(b!==d){h=Cl(Cu(b));i=Cl(Cu(d));if(h!==null&&i!==null){if(h===i)break b;if(!B8(h)&&!B8(i)){j=b;k=0;g=c;while(k<f){l=j.data;m=g+1|0;n=l[g];if(!Ej(i,n)){CC(b,c,d,e,k);H(CP());}k=k+1|0;g=m;}CC(b,c,d,e,f);return;}if(!B8(h))break a;if(B8(i))break b;else break a;}H(CP());}}CC(b,c,d,e,f);return;}H(CP());}}H(B$());}H(Hr(I(1)));},BP
=(b,c,d,e,f)=>{let g;if(c>=0&&e>=0&&f>=0&&(c+f|0)<=Cx(b)){g=e+f|0;if(g<=Cx(d)){CC(b,c,d,e,f);return;}}H(B$());},CC=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}};
function FZ(){let a=this;F.call(a);a.gn=null;a.gF=null;a.gl=0;a.gJ=0;}
let Fj=(a,b,c)=>{J(a);a.gn=b;a.gF=c;},K$=(a,b)=>{let c=new FZ();Fj(c,a,b);return c;},ID=a=>{return Bh(a.gn);},II=(a,b)=>{return O(a.gF)<b?0:1;},JC=(a,b)=>{a.gl=b;},Ng=(a,b)=>{a.gJ=b;};
function B6(){BS.call(this);this.fL=0;}
let I2=null,Ch=null,BM=()=>{BM=X(B6);IR();},Eg=(a,b)=>{BM();GC(a);a.fL=b;},Fs=a=>{let b=new B6();Eg(b,a);return b;},JK=b=>{BM();return b;},M5=b=>{BM();return IV(b,4);},BH=b=>{BM();if(b>=(-128)&&b<=127){KH();return Ch.data[b+128|0];}return Fs(b);},KH=()=>{let b;BM();a:{if(Ch===null){Ch=Bd(B6,256);b=0;while(true){if(b>=Ch.data.length)break a;Ch.data[b]=Fs(b-128|0);b=b+1|0;}}}},Kh=a=>{return a.fL;},IG=a=>{return JK(a.fL);},Me=(a,b)=>{if(a===b)return 1;return b instanceof B6&&b.fL==a.fL?1:0;},KD=b=>{let c,d,e;BM();if
(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;e=d>>>8|0;if(!e)e=d;else c=c|8;d=e>>>4|0;if(!d)d=e;else c=c|4;e=d>>>2|0;if(!e)e=d;else c=c|2;if(e>>>1|0)c=c|1;return (32-c|0)-1|0;},IR=()=>{I2=BW(Cn);},Er=G(Ba),GM=a=>{Cd(a);},Jq=()=>{let a=new Er();GM(a);return a;},Gl=G(),Ix=null,IA=null,FY=null,Ea=()=>{Ea=X(Gl);LS();},LS=()=>{Ix=DR([Bg(1),Bg(10),Bg(100),Bg(10000),Bg(100000000),Df(1874919424, 2328306)]);IA=Kd();FY=JW();},DO=G(),I1=null,LV=null,Bp=()=>{Bp=X(DO);JO();},FQ=b=>{Bp();return (b&64512)!=55296?0:1;},Fw
=b=>{Bp();return (b&64512)!=56320?0:1;},GB=b=>{Bp();return !FQ(b)&&!Fw(b)?0:1;},Kk=(b,c)=>{Bp();return ((b&1023)<<10|c&1023)+65536|0;},Na=b=>{let c;Bp();c=b-65536|0;return (55296|c>>10&1023)&65535;},J_=b=>{Bp();return (56320|b&1023)&65535;},D1=(b,c)=>{Bp();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},JO=()=>{I1=BW(Gb);LV=Bd(DO,128);};
function HB(){let a=this;F.call(a);a.fj=0;a.gd=0;a.go=null;}
let G6=(a,b)=>{J(a);a.go=H1();a.fj=b;a.gd=a.fj/2|0;},B0=a=>{let b=new HB();G6(b,a);return b;},Mo=(a,b)=>{return FC(b,a.fj);},FC=(b,c)=>{let d;d=b%c|0;if(d<0)d=d+c|0;return d;},Jf=(a,b)=>{return a.D(b+a.gd|0)-a.gd|0;},MW=(a,b)=>{let c,d,e,f,g;c=a.D(b);if(c==1)return c;if(!c){d=new Ci;c=a.fj;e=Q();M(K(e,I(2)),c);Cj(d,P(e));H(d);}f=(a.go.F(BH(c),Mu(a))).I();if(f)return f;d=new Ci;g=a.fj;e=Q();M(K(M(e,c),I(3)),g);Cj(d,P(e));H(d);},IM=(a,b)=>{let c,d,e,f,g,h,i,j,k,l;c=Cs();d=a.fj;e=b.I();while(true){c.J(BH(d/e|0));f
=d%e|0;if(f==1)break;if(!f)break;d=e;e=f;}if(!f)return BH(0);g=0;h=1;i=0;j=c.K();while(j.L()){k=(j.M()).I();l=V(k,h)+i|0;g=l;i=h;h=l;}if((c.N()%2|0)==1)g=a.D( -g|0);return BH(g);},HM=G(BS),Mq=null,EP=()=>{EP=X(HM);Kx();},JY=(b,c)=>{return Ju(b,c);},Kx=()=>{Mq=BW(EY);},EV=G(0),CX=(a,b,c)=>{let d,e;EQ(c);d=a.P(b);if(d!==null)return d;e=c.Q(b);if(e!==null)a.R(b,e);return e;},DP=G(0);
function Hs(){F.call(this);this.gw=null;}
let Gr=(a,b)=>{J(a);a.gw=b;},Mu=a=>{let b=new Hs();Gr(b,a);return b;},Jl=(a,b)=>{return FL(a,b);},FL=(a,b)=>{return IM(a.gw,b);},CQ=G(0);
function HL(){let a=this;F.call(a);a.gG=null;a.fQ=0;}
let Fb=(a,b)=>{J(a);a.gG=b;},Mm=a=>{let b=new HL();Fb(b,a);return b;},J2=(a,b)=>{let c,d;c=a.gG.data;d=a.fQ;a.fQ=d+1|0;c[d]=b;return 1;},Ho=G(0),Dl=G(0),HI=G(0),Dx=G(),Gi=a=>{J(a);},Mg=a=>{let b,c,d,e,f,g;b=a.U();if(b>=0){c=U(b);d=Mm(c);while(a.W(d)){}e=c.data;if(d.fQ<e.length)c=BK(c,d.fQ);return c;}f=Cs();while(true){EQ(f);if(!a.W(Lt(f)))break;}c=U(f.N());g=0;while(true){e=c.data;if(g>=e.length)break;e[g]=(f.Z(g)).I();g=g+1|0;}return c;},Gz=G(N),Fz=a=>{Y(a);},Mh=()=>{let a=new Gz();Fz(a);return a;},D2=G(0),Ef
=G(),HY=a=>{J(a);},Kn=()=>{let a=new Ef();HY(a);return a;},Iq=(a,b)=>{return FP(a,b);},FP=(a,b)=>{return b.I();},Cv=G(0);
function B7(){let a=this;F.call(a);a.gH=0;a.ff=0;a.ft=0;a.fO=0;}
let C5=(a,b)=>{J(a);a.fO=(-1);a.gH=b;a.ft=b;},CW=a=>{return a.gH;},Bi=a=>{return a.ff;},De=(a,b)=>{let c,d,e;if(b>=0&&b<=a.ft){a.ff=b;if(b<a.fO)a.fO=0;return a;}c=new Bl;d=a.ft;e=Q();BN(M(K(M(K(e,I(4)),b),I(5)),d),93);BV(c,P(e));H(c);},C_=a=>{return a.ft;},DY=a=>{a.ft=a.ff;a.ff=0;a.fO=(-1);return a;},O=a=>{return a.ft-a.ff|0;},Bh=a=>{return a.ff>=a.ft?0:1;},Dr=G(0),H2=G(0),C8=G(B7),EB=(a,b,c,d)=>{C5(a,b);a.ff=c;a.ft=d;},G_=b=>{let c,d;if(b>=0)return Kv(b);c=new Bl;d=Q();M(K(d,I(6)),b);BV(c,P(d));H(c);},Mr=(b,
c,d)=>{return LP(0,b.data.length,b,c,c+d|0,0);},Fa=b=>{return Mr(b,0,b.data.length);},J4=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;if(c>=0){e=b.data;f=e.length;if(c<=f){g=c+d|0;if(g>f){h=new T;i=Q();M(K(M(K(i,I(7)),g),I(8)),f);W(h,P(i));H(h);}if(O(a)<d)H(GD());if(d<0){i=new T;h=Q();K(M(K(h,I(9)),d),I(10));W(i,P(h));H(i);}j=a.ff;k=0;while(k<d){g=c+1|0;f=j+1|0;e[c]=a.be(j);k=k+1|0;c=g;j=f;}a.ff=a.ff+d|0;return a;}}e=b.data;i=new T;f=e.length;l=Q();BN(M(K(M(K(l,I(11)),c),I(5)),f),41);W(i,P(l));H(i);},Mn=(a,b)=>{return a.bf(b,
0,b.data.length);},M4=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;if(a.bg())H(CS());if(O(a)<d)H(DT());if(c>=0){e=b.data;f=e.length;if(c<=f){g=c+d|0;if(g>f){h=new T;i=Q();M(K(M(K(i,I(12)),g),I(8)),f);W(h,P(i));H(h);}if(d<0){i=new T;h=Q();K(M(K(h,I(9)),d),I(10));W(i,P(h));H(i);}j=a.ff;k=0;while(k<d){g=j+1|0;l=c+1|0;a.bh(j,e[c]);k=k+1|0;j=g;c=l;}a.ff=a.ff+d|0;return a;}}e=b.data;i=new T;f=e.length;h=Q();BN(M(K(M(K(h,I(11)),c),I(5)),f),41);W(i,P(h));H(i);},KT=(a,b,c,d)=>{let e,f,g,h,i,j;if(a.bg())H(CS());e=d-c|0;if(O(a)<e)H(DT());if
(c>=0&&c<=b.bi()){if(d>b.bi()){f=new T;g=b.bi();h=Q();M(K(M(K(h,I(12)),d),I(13)),g);W(f,P(h));H(f);}if(c>d){f=new T;h=Q();M(K(M(K(h,I(14)),c),I(15)),d);W(f,P(h));H(f);}i=a.ff;while(c<d){j=i+1|0;g=c+1|0;a.bh(i,b.bj(c));i=j;c=g;}a.ff=a.ff+e|0;return a;}f=new T;g=b.bi();h=Q();BN(M(K(M(K(h,I(14)),c),I(5)),g),41);W(f,P(h));H(f);},Cm=(a,b)=>{return a.bk(b,0,b.bi());},GX=a=>{return a.bl();},DS=a=>{return a.bm();},E0=a=>{DY(a);return a;},Ii=(a,b)=>{De(a,b);return a;},CR=G(C8),HG=(a,b,c,d)=>{EB(a,b,c,d);},Mt=a=>{return a.bq();};
function DE(){let a=this;CR.call(a);a.gP=0;a.f2=0;a.f0=null;}
let Gy=(a,b)=>{Eb(a,0,b,Bt(b),0,b,0);},Kv=a=>{let b=new DE();Gy(b,a);return b;},Eb=(a,b,c,d,e,f,g)=>{HG(a,c,e,f);a.f2=b;a.gP=g;a.f0=d;},LP=(a,b,c,d,e,f)=>{let g=new DE();Eb(g,a,b,c,d,e,f);return g;},KF=(a,b)=>{return a.f0.data[b+a.f2|0];},Ig=(a,b,c)=>{a.f0.data[b+a.f2|0]=c;},Ku=a=>{return 1;},JD=a=>{return a.f0;},L2=a=>{return a.gP;},Fd=G(0),Ct=G(0),By=a=>{return Ir(a);},BC=a=>{return Kr(a.bt());},Hn=G(0),G0=G(T),E_=a=>{DQ(a);},Hl=()=>{let a=new G0();E_(a);return a;};
function Dq(){let a=this;F.call(a);a.gY=null;a.gh=0.0;a.g9=0.0;a.fy=null;a.fE=null;a.fM=null;a.fr=0;}
let HK=(a,b,c,d)=>{let e,f;J(a);a.fy=I(16);Bj();a.fE=BF;a.fM=BF;if(c<=0.0){e=new Bl;f=Q();Do(K(f,I(17)),c);BV(e,P(f));H(e);}if(d>0.0){a.gY=b;a.gh=c;a.g9=d;return;}e=new Bl;f=Q();Do(K(f,I(18)),d);BV(e,P(f));H(e);},FE=(a,b)=>{if(b!==null){a.fE=b;a.bv(b);return a;}H(BX(I(19)));},Kl=(a,b)=>{return;},FI=(a,b)=>{if(b!==null){a.fM=b;a.bw(b);return a;}H(BX(I(19)));},KL=(a,b)=>{return;},C6=(a,b,c,d)=>{let e,f,g,$$je;if(!(a.fr==2&&!d)&&a.fr!=3){a.fr=d?2:1;while(true){try{e=a.bx(b,c);}catch($$e){$$je=BL($$e);if($$je instanceof N)
{f=$$je;H(HZ(f));}else{throw $$e;}}if(e.bz())return e;if(e.bA()){if(d&&Bh(b)){g=a.fE;Bj();if(g===BF)return Bw(O(b));if(O(c)<=a.fy.bi())return Bc;b.bC(Bi(b)+O(b)|0);if(a.fE===Bo)Cm(c,a.fy);}return e;}if(e.bF()){g=a.fE;Bj();if(g===BF)return e;if(a.fE===Bo){if(O(c)<a.fy.bi())return Bc;Cm(c,a.fy);}b.bC(Bi(b)+e.bi()|0);}else if(e.bG()){g=a.fM;Bj();if(g===BF)break;if(a.fM===Bo){if(O(c)<a.fy.bi())return Bc;Cm(c,a.fy);}b.bC(Bi(b)+e.bi()|0);}}return e;}H(Cc());},Hj=(a,b)=>{if(a.fr!=3&&a.fr!=2)H(Cc());a.fr=3;return a.bH(b);},Ga
=a=>{a.fr=0;a.bI();return a;},Hc=(a,b)=>{let c,d,e;if(a.fr&&a.fr!=3)H(Cc());if(!O(b))return G_(0);if(a.fr)Ga(a);c=G_(BQ(8,O(b)*a.gh|0));while(true){d=C6(a,b,c,0);if(d.bA())break;if(d.bz())c=Et(a,c);if(!d.bO())continue;d.bP();}e=C6(a,b,c,1);if(e.bO())e.bP();while(true){e=Hj(a,c);if(e.bA())break;c=Et(a,c);}E0(c);return c;},Et=(a,b)=>{let c,d,e;c=DS(b);d=c.data;d=FT(c,BQ(8,d.length*2|0));e=Fa(d);e.bV(Bi(b));return e;},Jp=(a,b)=>{R();return Bb;},IB=a=>{return;};
function Em(){let a=this;Dx.call(a);a.f1=null;a.gg=null;}
let HW=(a,b,c)=>{Gi(a);a.f1=b;a.gg=c;},LK=(a,b)=>{let c=new Em();HW(c,a,b);return c;},Mp=(a,b)=>{return a.f1.bW(M0(a,b));},Ki=a=>{return a.f1.U();},If=(a,b,c)=>{return b.bY(a.gg.bZ(c));},FS=G(),Dt=null,JE=null,L5=null,Lc=null,MJ=null,Nc=null,Ck=()=>{Ck=X(FS);JH();},JH=()=>{Cp();Dt=HR;JE=L1();L5=Nj();Lc=D0(I(20),1,0);MJ=D0(I(21),0,0);Nc=D0(I(22),0,1);};
function Dy(){F.call(this);this.g7=null;}
let GG=null,Mx=null,Cy=()=>{Cy=X(Dy);MX();},Ik=(a,b)=>{Cy();J(a);a.g7=b;},Ez=a=>{let b=new Dy();Ik(b,a);return b;},MX=()=>{GG=Ez(I(23));Mx=Ez(I(24));},FO=G(0);
function B9(){let a=this;F.call(a);a.fd=null;a.fk=0;}
let DD=a=>{Db(a,16);},Nz=()=>{let a=new B9();DD(a);return a;},Db=(a,b)=>{J(a);a.fd=Bt(b);},NJ=a=>{let b=new B9();Db(b,a);return b;},GE=(a,b)=>{return a.b1(a.fk,b);},Ei=(a,b,c)=>{let d,e,f;if(b>=0&&b<=a.fk){if(c===null)c=I(25);else if(c.b2())return a;a.b3(a.fk+c.bi()|0);d=a.fk-1|0;while(d>=b){a.fd.data[d+c.bi()|0]=a.fd.data[d];d=d+(-1)|0;}a.fk=a.fk+c.bi()|0;d=0;while(d<c.bi()){e=a.fd.data;f=b+1|0;e[b]=c.bj(d);d=d+1|0;b=f;}return a;}H(Hl());},Gs=(a,b)=>{return a.b4(b,10);},J3=(a,b,c)=>{return a.b5(a.fk,b,c);},Lz
=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;e=1;if(c<0){e=0;c= -c|0;}a:{if(Br(c,d)<0){if(e)Bn(a,b,b+1|0);else{Bn(a,b,b+2|0);f=a.fd.data;g=b+1|0;f[b]=45;b=g;}a.fd.data[b]=D1(c,d);}else{h=1;i=1;j=Be((-1),d);b:{while(true){k=V(h,d);if(Br(k,c)>0){k=h;break b;}i=i+1|0;if(Br(k,j)>0)break;h=k;}}if(!e)i=i+1|0;Bn(a,b,b+i|0);if(e)l=b;else{f=a.fd.data;l=b+1|0;f[b]=45;}while(true){if(!k)break a;f=a.fd.data;g=l+1|0;f[l]=D1(Be(c,k),d);c=M_(c,k);k=Be(k,d);l=g;}}}return a;},EG=(a,b)=>{return a.b8(a.fk,b);},Fy=(a,b,c)=>{let d,e,f,g,h,
i,j,k,l,m,n,o,p,q,r,s,t,u;d=E3(c,0.0);if(!d){if(1.0/c===Infinity){Bn(a,b,b+3|0);e=a.fd.data;d=b+1|0;e[b]=48;e=a.fd.data;f=d+1|0;e[d]=46;a.fd.data[f]=48;return a;}Bn(a,b,b+4|0);e=a.fd.data;d=b+1|0;e[b]=45;e=a.fd.data;f=d+1|0;e[d]=48;e=a.fd.data;d=f+1|0;e[f]=46;a.fd.data[d]=48;return a;}if(isNaN(c)?1:0){Bn(a,b,b+3|0);e=a.fd.data;d=b+1|0;e[b]=78;e=a.fd.data;f=d+1|0;e[d]=97;a.fd.data[f]=78;return a;}if(!isFinite(c)?1:0){if(d>0){Bn(a,b,b+8|0);d=b;}else{Bn(a,b,b+9|0);e=a.fd.data;d=b+1|0;e[b]=45;}e=a.fd.data;f=d+1
|0;e[d]=73;e=a.fd.data;d=f+1|0;e[f]=110;e=a.fd.data;f=d+1|0;e[d]=102;e=a.fd.data;d=f+1|0;e[f]=105;e=a.fd.data;f=d+1|0;e[d]=110;e=a.fd.data;d=f+1|0;e[f]=105;e=a.fd.data;f=d+1|0;e[d]=116;a.fd.data[f]=121;return a;}Ea();g=FY;Jh(c,g);h=g.f5;i=g.ge;j=g.gE;k=1;l=1;if(j)l=2;m=9;n=Jj(h);if(n>0)m=m-n|0;o=0;p=0;if(i<7&&i>=(-3)){if(i>=0){k=i+1|0;m=BQ(m,k+1|0);i=0;}else{k=0;o=( -i|0)-1|0;p=1;l=l+1|0;i=0;}}if(i){l=l+2|0;if(!(i>(-10)&&i<10))l=l+1|0;if(i<0)l=l+1|0;}if(i&&m==k)m=m+1|0;d=l+(m+o|0)|0;Bn(a,b,b+d|0);if(!j)q=b;else
{e=a.fd.data;q=b+1|0;e[b]=45;}r=100000000;if(p){e=a.fd.data;d=q+1|0;e[q]=48;e=a.fd.data;q=d+1|0;e[d]=46;while(true){d=o+(-1)|0;if(o<=0)break;e=a.fd.data;f=q+1|0;e[q]=48;o=d;q=f;}}s=0;while(s<m){if(r<=0)t=0;else{t=h/r|0;h=h%r|0;}e=a.fd.data;f=q+1|0;e[q]=(48+t|0)&65535;k=k+(-1)|0;if(k)q=f;else{e=a.fd.data;q=f+1|0;e[f]=46;}r=r/10|0;s=s+1|0;}if(i){e=a.fd.data;d=q+1|0;e[q]=69;if(i>=0)f=d;else{i= -i|0;e=a.fd.data;f=d+1|0;e[d]=45;}if(i<10)u=f;else{e=a.fd.data;u=f+1|0;e[f]=(48+(i/10|0)|0)&65535;}a.fd.data[u]=(48+(i
%10|0)|0)&65535;}return a;},Jj=b=>{let c,d,e,f;if(!(b%1000000000|0))return 9;c=0;d=1;if(!(b%100000000|0)){c=8;d=100000000;}e=d*10000|0;if(b%e|0)e=d;else c=c|4;f=e*100|0;if(b%f|0)f=e;else c=c|2;if(!(b%(f*10|0)|0))c=c|1;return c;},Hh=(a,b)=>{return a.b_(a.fk,b);},GU=(a,b,c)=>{Bn(a,b,b+1|0);a.fd.data[b]=c;return a;},ES=(a,b,c)=>{return a.ca(b,c===null?I(25):c.f());},Gh=(a,b)=>{let c;if(a.fd.data.length>=b)return;c=a.fd.data.length>=1073741823?2147483647:BQ(b,BQ(a.fd.data.length*2|0,5));a.fd=FT(a.fd,c);},E7=a=>
{return Mb(a.fd,0,a.fk);},Bn=(a,b,c)=>{let d,e;d=a.fk-b|0;a.b3((a.fk+c|0)-b|0);e=d-1|0;while(e>=0){a.fd.data[c+e|0]=a.fd.data[b+e|0];e=e+(-1)|0;}a.fk=a.fk+(c-b|0)|0;},EJ=G(B9),G1=a=>{DD(a);},Q=()=>{let a=new EJ();G1(a);return a;},K=(a,b)=>{GE(a,b);return a;},M=(a,b)=>{Gs(a,b);return a;},Do=(a,b)=>{EG(a,b);return a;},BN=(a,b)=>{Hh(a,b);return a;},I$=(a,b,c)=>{Fy(a,b,c);return a;},Ms=(a,b,c)=>{ES(a,b,c);return a;},Kg=(a,b,c)=>{GU(a,b,c);return a;},MF=(a,b,c)=>{Ei(a,b,c);return a;},P=a=>{return E7(a);},MU=(a,b)=>
{Gh(a,b);},I6=(a,b,c)=>{return a.cg(b,c);},It=(a,b,c)=>{return a.ch(b,c);},KE=(a,b,c)=>{return a.ci(b,c);},M7=(a,b,c)=>{return a.cj(b,c);},Eo=G(),En=()=>{En=X(Eo);L0();},L0=()=>{return;},Fv=G(N),Hw=a=>{Y(a);},GO=()=>{let a=new Fv();Hw(a);return a;},Fc=G(0),G9=G(0);
function Dg(){F.call(this);this.gi=null;}
let Eu=(a,b)=>{J(a);a.gi=b;},Nv=a=>{let b=new Dg();Eu(b,a);return b;},JV=(a,b)=>{return JJ(b,a.gi);},IT=(a,b)=>{let c,d,e;c=Bf(b.bi());d=0;while(true){e=c.data;if(d>=e.length)break;e[d]=b.bj(d)<<24>>24;d=d+1|0;}return a.cl(c);};
function Bs(){let a=this;F.call(a);a.gW=null;a.g1=null;}
let Ce=(a,b,c)=>{let d,e,f,g;d=c.data;J(a);HQ(b);e=d.length;f=0;while(f<e){g=d[f];HQ(g);f=f+1|0;}a.gW=b;a.g1=c.cn();},HQ=b=>{let c,d;if(b.b2())H(Da(b));if(!HU(b.bj(0)))H(Da(b));c=1;while(c<b.bi()){a:{d=b.bj(c);switch(d){case 43:case 45:case 46:case 58:case 95:break;default:if(HU(d))break a;else H(Da(b));}}c=c+1|0;}},HU=b=>{let c;a:{b:{if(!(b>=48&&b<=57)&&!(b>=97&&b<=122)){if(b<65)break b;if(b>90)break b;}c=1;break a;}c=0;}return c;},EM=(a,b)=>{let c,d,e,$$je;a:{try{c=a.cp();Bj();d=Bo;d=FE(c,d);c=Bo;d=FI(d,c);d
=Hc(d,b);}catch($$e){$$je=BL($$e);if($$je instanceof BJ){e=$$je;break a;}else{throw $$e;}}return d;}H(E2(I(26),e));},GQ=(a,b)=>{let c,d,e,$$je;a:{try{c=a.ct();Bj();d=Bo;d=Ed(c,d);c=Bo;d=Gq(d,c);d=Ex(d,b);}catch($$e){$$je=BL($$e);if($$je instanceof BJ){e=$$je;break a;}else{throw $$e;}}return d;}H(E2(I(26),e));},EI=G(Bs),HC=a=>{Ce(a,I(27),Bd(Z,0));},Nj=()=>{let a=new EI();HC(a);return a;},BI=G(BB),DW=a=>{Di(a);},NF=()=>{let a=new BI();DW(a);return a;},DK=(a,b,c)=>{D4(a,b,c);},Nw=(a,b)=>{let c=new BI();DK(c,a,
b);return c;},Dz=(a,b)=>{FK(a,b);},NE=a=>{let b=new BI();Dz(b,a);return b;},Ci=G(Ba),Cj=(a,b)=>{B5(a,b);},IL=a=>{let b=new Ci();Cj(b,a);return b;},DC=G(BI),FJ=a=>{DW(a);},Fg=()=>{let a=new DC();FJ(a);return a;},Ib=(a,b,c)=>{DK(a,b,c);},E2=(a,b)=>{let c=new DC();Ib(c,a,b);return c;},L3=G(N),B4=G(),Ds=a=>{J(a);},Hu=G(0),EU=G(0);
function DB(){B4.call(this);this.fz=0;}
let GN=a=>{Ds(a);},IZ=a=>{return Km(a);},Cg=G(0),Gv=G(0);
function Dw(){let a=this;DB.call(a);a.fn=null;a.fq=0;}
let Fn=a=>{C1(a,10);},Cs=()=>{let a=new Dw();Fn(a);return a;},C1=(a,b)=>{GN(a);if(b>=0){a.fn=Bd(F,b);return;}H(BR());},Nx=a=>{let b=new Dw();C1(b,a);return b;},JM=(a,b)=>{let c;if(a.fn.data.length<b){c=a.fn.data.length>=1073741823?2147483647:BQ(b,BQ(a.fn.data.length*2|0,5));a.fn=LB(a.fn,c);}},MT=(a,b)=>{IX(a,b);return a.fn.data[b];},K1=a=>{return a.fq;},KW=(a,b)=>{let c,d;a.b3(a.fq+1|0);c=a.fn.data;d=a.fq;a.fq=d+1|0;c[d]=b;a.fz=a.fz+1|0;return 1;},LQ=(a,b,c)=>{let d;Nb(a,b);a.b3(a.fq+1|0);d=a.fq;while(d>b){a.fn.data[d]
=a.fn.data[d-1|0];d=d+(-1)|0;}a.fn.data[b]=c;a.fq=a.fq+1|0;a.fz=a.fz+1|0;},IX=(a,b)=>{if(b>=0&&b<a.fq)return;H(B$());},Nb=(a,b)=>{if(b>=0&&b<=a.fq)return;H(B$());},Gc=G(BI),EX=(a,b)=>{Dz(a,b);},HZ=a=>{let b=new Gc();EX(b,a);return b;},FM=G(),Hq=a=>{J(a);},LA=()=>{let a=new FM();Hq(a);return a;},K_=(a,b)=>{return H8(a,b);},H8=(a,b)=>{return LT(b);},Cq=G(),C2=a=>{J(a);},NH=()=>{let a=new Cq();C2(a);return a;},Ks=(a,b)=>{if(b<=0)H(BR());return a.cE()*b|0;},I3=a=>{return Jy();},D$=G(Cq),F$=null,CE=()=>{CE=X(D$);Io();},JF
=a=>{CE();C2(a);},MA=()=>{let a=new D$();JF(a);return a;},LR=()=>{CE();return F$;},Io=()=>{F$=MA();},Z=G(),K2=null,I5=null,IU=null,BU=()=>{BU=X(Z);Kb();},E1=a=>{BU();J(a);a.fp="";},KC=()=>{let a=new Z();E1(a);return a;},Fm=(a,b)=>{let c;BU();c=b.data;J(a);a.fp=Dm(b.data,0,c.length);},Ey=a=>{let b=new Z();Fm(b,a);return b;},FG=(a,b)=>{a.fp=b;},Lo=a=>{let b=new Z();FG(b,a);return b;},H$=(a,b,c,d)=>{let e;BU();e=b.data;J(a);Hy(c,d,e.length);a.fp=Dm(b.data,c,d);},Mb=(a,b,c)=>{let d=new Z();H$(d,a,b,c);return d;},Dc
=(a,b,c)=>{let d;BU();d=b.data;J(a);L$(a,b,0,d.length,c);},Nr=(a,b)=>{let c=new Z();Dc(c,a,b);return c;},L$=(a,b,c,d,e)=>{let f,g;f=EM(e,GT(b,c,d));if(GX(f)&&!Bi(f)&&C_(f)==CW(f))g=DS(f);else{g=Bt(O(f));f.cM(g);}a.fp=Iy(g.data);},KI=(a,b)=>{if(b>=0&&b<a.fp.length)return a.fp.charCodeAt(b);H(Hl());},JG=a=>{return a.fp.length;},L8=a=>{return a.fp.length?0:1;};
let LN=a=>{return a;},Ke=(a,b)=>{let c,d;c=GQ(b,Fa(K8(a.fp)));if(c.cJ()&&!Bi(c)&&C_(c)==CW(c))return DL(c);d=Bf(O(c));c.cO(d);return d;},Kb=()=>{K2=Bt(0);I5=KC();IU=La();},Id=G(N),Gk=a=>{Y(a);},K0=()=>{let a=new Id();Gk(a);return a;};
function CK(){let a=this;F.call(a);a.g2=null;a.f6=null;a.gA=0.0;a.gf=0.0;a.f$=null;a.f_=null;a.fv=0;}
let Gx=(a,b,c,d,e)=>{J(a);Bj();a.f$=BF;a.f_=BF;Lb(a,e);a.g2=b;a.f6=e.cn();a.gA=c;a.gf=d;},FF=(a,b,c,d)=>{let e;e=Bf(1);e.data[0]=63;Gx(a,b,c,d,e);},Lb=(a,b)=>{let c;if(b!==null){c=b.data.length;if(c&&c>=a.gf)return;}H(BX(I(28)));},Ed=(a,b)=>{if(b!==null){a.f$=b;a.bv(b);return a;}H(BX(I(29)));},L9=(a,b)=>{return;},Gq=(a,b)=>{if(b!==null){a.f_=b;a.bw(b);return a;}H(BX(I(29)));},Lx=(a,b)=>{return;},Dv=(a,b,c,d)=>{let e,f,g,h,$$je;a:{if(a.fv!=3){if(d)break a;if(a.fv!=2)break a;}H(Cc());}a.fv=!d?1:2;while(true){try
{e=a.cR(b,c);}catch($$e){$$je=BL($$e);if($$je instanceof N){f=$$je;H(HZ(f));}else{throw $$e;}}if(e.bA()){if(!d)return e;g=O(b);if(g<=0)return e;e=Bw(g);}else if(e.bz())break;h=!e.bG()?a.f$:a.f_;b:{Bj();if(h!==Bo){if(h===E9)break b;else return e;}if(O(c)<a.f6.data.length)return Bc;Fp(c,a.f6);}b.bV(Bi(b)+e.bi()|0);}return e;},Ex=(a,b)=>{let c,d,e;if(!O(b))return HJ(0);EL(a);c=HJ(O(b)*a.gA|0);while(true){d=Dv(a,b,c,0);R();if(d===Bb)break;if(d===Bc){c=FX(a,c);continue;}if(!d.bO())continue;d.bP();}e=Dv(a,b,c,1);if
(e.bO())e.bP();while(true){e=ET(a,c);if(e.bA())break;if(!e.bz())continue;c=FX(a,c);}Fq(c);return c;},FX=(a,b)=>{let c,d,e;c=DL(b);d=c.data;d=F2(c,d.length*2|0);e=Iu(d);e.bC(Bi(b));return e;},ET=(a,b)=>{let c;if(a.fv!=2&&a.fv!=4)H(Cc());c=a.c1(b);R();if(c===Bb)a.fv=3;return c;},IK=(a,b)=>{R();return Bb;},EL=a=>{a.fv=0;a.bI();return a;},KQ=a=>{return;};
function Ec(){let a=this;CK.call(a);a.gq=null;a.gI=null;}
let Hp=(a,b,c,d)=>{FF(a,b,c,d);a.gq=Bt(512);a.gI=Bf(512);},KR=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n;d=a.gq;e=0;f=0;g=a.gI;a:{while(true){if((e+32|0)>f&&Bh(b)){h=e;while(h<f){i=d.data;i[h-e|0]=i[h];h=h+1|0;}i=d.data;j=f-e|0;f=Bm(O(b)+j|0,i.length);b.bf(d,j,f-j|0);e=0;}if(!Bh(c)){if(!Bh(b)&&e>=f){R();k=Bb;}else{R();k=Bc;}break a;}i=g.data;l=0;m=Bm(O(c),i.length);n=K$(b,c);k=a.c4(d,e,f,g,l,m,n);e=n.gl;j=n.gJ;if(k===null){if(!Bh(b)&&e>=f){R();k=Bb;}else if(!Bh(c)&&e>=f){R();k=Bc;}}c.c5(g,0,j);if(k!==null)break;}}b.bV(Bi(b)
-(f-e|0)|0);return k;},H5=G(Ec),EF=(a,b)=>{Hp(a,b,2.0,4.0);},IE=a=>{let b=new H5();EF(b,a);return b;},MQ=(a,b,c,d,e,f,g,h)=>{let i,j,k,l,m,n,o,p,q;i=null;a:{while(c<d){if(f>=g){j=c;break a;}k=b.data;j=c+1|0;l=k[c];if(l<128){k=e.data;m=f+1|0;k[f]=l<<24>>24;}else if(l<2048){if((f+2|0)>g){j=j+(-1)|0;if(h.c6(2))break a;R();i=Bc;break a;}k=e.data;n=f+1|0;k[f]=(192|l>>6)<<24>>24;m=n+1|0;k[n]=(128|l&63)<<24>>24;}else if(!GB(l)){if((f+3|0)>g){j=j+(-1)|0;if(h.c6(3))break a;R();i=Bc;break a;}k=e.data;o=f+1|0;k[f]=(224
|l>>12)<<24>>24;n=o+1|0;k[o]=(128|l>>6&63)<<24>>24;m=n+1|0;k[n]=(128|l&63)<<24>>24;}else{if(!FQ(l)){i=Bw(1);break a;}if(j>=d){if(h.c8())break a;R();i=Bb;break a;}n=j+1|0;p=k[j];if(!Fw(p)){j=n+(-2)|0;i=Bw(1);break a;}if((f+4|0)>g){j=n+(-2)|0;if(h.c6(4))break a;R();i=Bc;break a;}k=e.data;q=Kk(l,p);j=f+1|0;k[f]=(240|q>>18)<<24>>24;o=j+1|0;k[j]=(128|q>>12&63)<<24>>24;j=o+1|0;k[o]=(128|q>>6&63)<<24>>24;m=j+1|0;k[j]=(128|q&63)<<24>>24;j=n;}c=j;f=m;}j=c;}h.c$(j);h.c_(f);return i;},Cr=G(N),CY=a=>{Y(a);},J6=()=>{let a
=new Cr();CY(a);return a;},Ek=G(0);
function G5(){F.call(this);this.gO=null;}
let HX=(a,b)=>{J(a);a.gO=b;},Lt=a=>{let b=new G5();HX(b,a);return b;},Lk=(a,b)=>{return a.gO.J(BH(b));};
function DM(){let a=this;F.call(a);a.gV=null;a.gK=0;}
let EK=(a,b,c)=>{J(a);a.gV=b;a.gK=c;},NL=(a,b)=>{let c=new DM();EK(c,a,b);return c;},Ih=(a,b)=>{return MK(b,a.gV,a.gK);},JU=(a,b)=>{let c,d,e,f,g;c=a.db(b);d=c.data;e=d.length;f=Bt(e);g=0;while(g<e){f.data[g]=d[g]&255&65535;g=g+1|0;}return Ey(f);};
function FA(){F.call(this);this.fN=0;}
let GV=a=>{J(a);a.fN=0;},KZ=()=>{let a=new FA();GV(a);return a;},My=a=>{a.fN=a.fN+1|0;},Lf=a=>{return a.fN;},B_=G(Ba),Es=(a,b)=>{B5(a,b);},JP=a=>{let b=new B_();Es(b,a);return b;},D5=G(Bs),HR=null,Cp=()=>{Cp=X(D5);IQ();},Lu=a=>{Cp();Ce(a,I(30),Bd(Z,0));},K7=()=>{let a=new D5();Lu(a);return a;},Ip=a=>{return Mv(a);},Ly=a=>{return IE(a);},IQ=()=>{HR=K7();},D9=G(0);
function FN(){let a=this;F.call(a);a.fP=0;a.gz=0;a.gB=0;a.gp=0;a.fK=null;}
let Gw=(a,b)=>{a.fK=b;J(a);a.gz=a.fK.fz;a.gB=a.fK.N();a.gp=(-1);},Km=a=>{let b=new FN();Gw(b,a);return b;},Jr=a=>{return a.fP>=a.gB?0:1;},J0=a=>{let b,c;MI(a);a.gp=a.fP;b=a.fK;c=a.fP;a.fP=c+1|0;return b.Z(c);},MI=a=>{if(a.gz>=a.fK.fz)return;H(GO());},Hx=G(Cr),G8=a=>{CY(a);},CS=()=>{let a=new Hx();G8(a);return a;},Fl=G(N),EH=a=>{Y(a);},Cc=()=>{let a=new Fl();EH(a);return a;},Jz=G(),Cx=b=>{if(b===null||b.constructor.$meta.item==='undefined'){H(BR());}return b.data.length;},L7=(b,c)=>{if(b===null)H(LC());if(b===
BW(K3))H(BR());if(c<0)H(K0());return Lp(Gf(b),c);},Lp=(b,c)=>{if(b.$meta.primitive){switch(b){};}return Bd(b,c);},EN=G(0);
function GH(){let a=this;F.call(a);a.gU=null;a.gN=0;}
let Gu=(a,b)=>{J(a);a.gU=b;},LL=a=>{let b=new GH();Gu(b,a);return b;},J$=(a,b)=>{a.gN=a.gU.dh(b);};
function CH(){let a=this;F.call(a);a.fA=0;a.gy=0;a.fu=null;a.fC=null;a.gx=null;a.fI=null;}
let CT=(a,b)=>{J(a);a.fI=b;a.gy=b.fD;a.fu=null;},Np=a=>{let b=new CH();CT(b,a);return b;},Jx=a=>{if(a.fu!==null)return 1;while(a.fA<a.fI.fi.data.length){if(a.fI.fi.data[a.fA]!==null)return 1;a.fA=a.fA+1|0;}return 0;},Ic=a=>{if(a.gy==a.fI.fD)return;H(GO());},GJ=a=>{let b,c;Ic(a);if(!a.L())H(Il());if(a.fu===null){b=a.fI.fi.data;c=a.fA;a.fA=c+1|0;a.fC=b[c];a.fu=a.fC.fx;a.gx=null;}else{if(a.fC!==null)a.gx=a.fC;a.fC=a.fu;a.fu=a.fu.fx;}},Gp=G(),GP=a=>{J(a);},Kd=()=>{let a=new Gp();GP(a);return a;};
function Ca(){F.call(this);this.fe=null;}
let D8=0,BD=()=>{BD=X(Ca);Jt();},F1=(a,b)=>{BD();J(a);a.fe=b;},Bq=a=>{let b=new Ca();F1(b,a);return b;},F3=(a,b,c,d)=>{let e,f,g,h;BD();e=b.data;J(a);f=e.length;g=E3(f,c);if(!g)a.fe=b;if(g>0)H(JP(I(31)));h=!d?c-f|0:0;a.fe=U(c);BP(b,0,a.fe,h,f);},DN=(a,b,c)=>{let d=new Ca();F3(d,a,b,c);return d;},KG=b=>{let c,d;BD();c=U(b);d=c.data;d[0]=1;return Bq(c);},DU=(b,c,d)=>{let e,f,g,h,i,j;BD();e=c+d|0;if(e>b)H(BX(I(32)));f=U(b);g=0;while(g<c){f.data[g]=1;g=g+1|0;}while(c<e){f.data[c]=(-1);c=c+1|0;}c=b-1|0;while(c>=
0){h=f.data;i=(LR()).dl(c+1|0);j=h[c];h[c]=h[i];h[i]=j;c=c+(-1)|0;}return Bq(f);},Ji=a=>{return Bq(BK(a.fe,a.fe.data.length));},MV=(a,b,c)=>{let d;BD();if(!D8&&a.fe.data.length!=b.fe.data.length)H(Fg());d=0;while(d<a.fe.data.length){a.fe.data[d]=c.D(a.fe.data[d]+b.fe.data[d]|0);d=d+1|0;}return a;},Iw=(a,b,c)=>{return MV(a.dn(),b,c);},Lq=(a,b,c)=>{let d,e,f,g,h,i;BD();if(!D8&&a.fe.data.length!=b.fe.data.length)H(Fg());d=a.fe.data.length;e=U(d);f=0;while(f<d){g=0;while(g<=f){h=e.data;h[f]=c.D(h[f]+V(a.fe.data[g],
b.fe.data[f-g|0])|0);g=g+1|0;}i=f+1|0;g=i;while(true){h=e.data;if(g>=h.length)break;h[f]=c.D(h[f]+V(a.fe.data[g],b.fe.data[(d+f|0)-g|0])|0);g=g+1|0;}f=i;}a.fe=e;return a;},JX=(a,b,c)=>{return Lq(a.dn(),b,c);},Nf=(a,b,c)=>{let d,e,f;d=BK(a.fe,a.fe.data.length);e=0;while(true){f=d.data;if(e>=f.length)break;f[e]=c.D(V(f[e],b));e=e+1|0;}return Bq(d);},Mz=(a,b)=>{let c,d,e,f;c=a.fe.data.length;d=BK(a.fe,a.fe.data.length);e=0;while(e<c){f=d.data;f[e]=b.dq(f[e]);e=e+1|0;}return Bq(d);},MB=(a,b)=>{let c,d,e,f;c=a.fe.data.length;d
=BK(a.fe,a.fe.data.length);e=0;while(e<c){f=d.data;f[e]=b.D(f[e]);e=e+1|0;}return Bq(d);},Jt=()=>{D8=G4(BW(Ca))?0:1;},C0=G(N),ER=(a,b)=>{Cb(a,b);},Hr=a=>{let b=new C0();ER(b,a);return b;},Hk=a=>{Y(a);},LC=()=>{let a=new C0();Hk(a);return a;};
function DX(){let a=this;B7.call(a);a.f8=0;a.fR=null;a.hb=null;}
let FR=(a,b,c,d,e,f)=>{C5(a,c);Cy();a.hb=GG;a.f8=b;a.fR=d;a.ff=e;a.ft=f;},HJ=b=>{let c,d;if(b>=0)return M2(b,0);c=new Bl;d=Q();M(K(d,I(6)),b);BV(c,P(d));H(c);},GT=(b,c,d)=>{let e;e=b.data.length;Hy(c,d,e);return I_(0,e,b,c,c+d|0,0,0);},Iu=b=>{return GT(b,0,b.data.length);},M3=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m;if(c>=0){e=b.data;f=e.length;if(c<=f){g=c+d|0;if(g>f){h=new T;i=Q();M(K(M(K(i,I(33)),g),I(8)),f);W(h,P(i));H(h);}if(O(a)<d)H(GD());if(d<0){j=new T;h=Q();K(M(K(h,I(9)),d),I(10));W(j,P(h));H(j);}k=a.ff+a.f8
|0;l=0;while(l<d){g=c+1|0;m=a.fR.data;f=k+1|0;e[c]=m[k];l=l+1|0;c=g;k=f;}a.ff=a.ff+d|0;return a;}}e=b.data;j=new T;f=e.length;h=Q();BN(M(K(M(K(h,I(11)),c),I(5)),f),41);W(j,P(h));H(j);},KV=(a,b)=>{return a.du(b,0,b.data.length);},KO=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;if(!d)return a;if(a.bg())H(CS());if(O(a)<d)H(DT());if(c>=0){e=b.data;f=e.length;if(c<=f){g=c+d|0;if(g>f){h=new T;i=Q();M(K(M(K(i,I(34)),g),I(8)),f);W(h,P(i));H(h);}if(d<0){h=new T;i=Q();K(M(K(i,I(9)),d),I(10));W(h,P(i));H(h);}j=a.ff+a.f8|0;k=0;while
(k<d){l=a.fR.data;g=j+1|0;f=c+1|0;l[j]=e[c];k=k+1|0;j=g;c=f;}a.ff=a.ff+d|0;return a;}}e=b.data;h=new T;f=e.length;i=Q();BN(M(K(M(K(i,I(11)),c),I(5)),f),41);W(h,P(i));H(h);},Fp=(a,b)=>{return a.c5(b,0,b.data.length);},K5=a=>{return 1;},DL=a=>{return a.fR;},Fq=a=>{DY(a);return a;},Jg=(a,b)=>{De(a,b);return a;};
function DF(){let a=this;Dq.call(a);a.gL=null;a.gD=null;}
let Gd=(a,b,c,d)=>{HK(a,b,c,d);a.gL=Bf(512);a.gD=Bt(512);},J8=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n;d=a.gL;e=0;f=0;g=a.gD;a:{while(true){if((e+32|0)>f&&Bh(b)){h=e;while(h<f){i=d.data;i[h-e|0]=i[h];h=h+1|0;}i=d.data;j=f-e|0;f=Bm(O(b)+j|0,i.length);b.du(d,j,f-j|0);e=0;}if(!Bh(c)){if(!Bh(b)&&e>=f){R();k=Bb;}else{R();k=Bc;}break a;}i=g.data;l=0;m=Bm(O(c),i.length);n=LI(b,c);k=a.dw(d,e,f,g,l,m,n);e=n.gM;if(k===null&&l==n.f9){R();k=Bb;}j=n.f9;c.dx(g,0,j);if(k!==null)break;}}b.bC(Bi(b)-(f-e|0)|0);return k;},FD=G(DF),HE
=(a,b)=>{Gd(a,b,0.3333333432674408,0.5);},Mv=a=>{let b=new FD();HE(b,a);return b;},Lv=(a,b,c,d,e,f,g,h)=>{let i,j,k,l,m,n,o,p,q,r,s;i=null;a:{b:{c:{while(c<d){if(f>=g)break a;j=b.data;k=c+1|0;l=j[c]&255;if(!(l&128)){j=e.data;m=f+1|0;j[f]=l&65535;}else if((l&224)==192){if(k>=d){c=k+(-1)|0;if(h.dy(2))break a;R();i=Bb;break a;}n=k+1|0;o=j[k];if(!BZ(a,o)){c=n+(-2)|0;i=Bw(1);break a;}j=e.data;m=f+1|0;j[f]=((l&31)<<6|o&63)&65535;k=n;}else if((l&240)==224){if((k+2|0)>d){c=k+(-1)|0;if(h.dy(3))break a;R();i=Bb;break a;}n
=k+1|0;o=j[k];k=n+1|0;p=j[n];if(!BZ(a,o))break b;if(!BZ(a,p))break b;q=((l&15)<<12|(o&63)<<6|p&63)&65535;if(GB(q)){c=k+(-3)|0;i=Bw(3);break a;}j=e.data;m=f+1|0;j[f]=q;}else{if((l&248)!=240){c=k+(-1)|0;i=Bw(1);break a;}if((k+3|0)>d){c=k+(-1)|0;if(h.dy(4))break a;R();i=Bb;break a;}if((f+2|0)>g){c=k+(-1)|0;if(h.c6(2))break a;R();i=Bc;break a;}n=k+1|0;o=j[k];m=n+1|0;p=j[n];k=m+1|0;r=j[m];if(!BZ(a,o))break c;if(!BZ(a,p))break c;if(!BZ(a,r))break c;j=e.data;s=(l&7)<<18|(o&63)<<12|(p&63)<<6|r&63;n=f+1|0;j[f]=Na(s);m
=n+1|0;j[n]=J_(s);}c=k;f=m;}break a;}c=k+(-3)|0;i=Bw(1);break a;}c=k+(-3)|0;i=Bw(1);}h.c$(c);h.c_(f);return i;},BZ=(a,b)=>{return (b&192)!=128?0:1;},GS=G(),Bv=null,BT=null,CD=null,CV=null,Bk=()=>{Bk=X(GS);LX();},JJ=(b,c)=>{let d,e,f,g,h,i;Bk();d=b.data;e=d.length;f=(e/4|0)*3|0;g=e%4|0;if(!(g!=2&&g!=3))f=f+(g-1|0)|0;h=e-1|0;while(h>=0&&d[h]==61){f=f+(-1)|0;h=h+(-1)|0;}i=Bf(f);J7(b,i,c);return i;},J7=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s;Bk();e=b.data;f=e.length;g=f-1|0;while(g>=0&&e[g]==61){f=f+(-1)|0;g
=g+(-1)|0;}h=(f/4|0)*4|0;i=0;j=0;while(i<h){k=c.data;l=i+1|0;m=BA(d,e[i]);i=l+1|0;n=BA(d,e[l]);l=i+1|0;o=BA(d,e[i]);i=l+1|0;p=BA(d,e[l]);q=m<<18|n<<12|o<<6|p;l=j+1|0;k[j]=(q>>>16|0)<<24>>24;r=l+1|0;k[l]=(q>>>8|0)<<24>>24;j=r+1|0;k[r]=q<<24>>24;}s=f-i|0;if(s==2){k=c.data;m=BA(d,e[i]);n=BA(d,e[i+1|0]);k[j]=(m<<2|(n>>>4|0))<<24>>24;}else if(s==3){k=c.data;m=BA(d,e[i]);n=BA(d,e[i+1|0]);o=BA(d,e[i+2|0]);k[j]=(m<<2|(n>>>4|0))<<24>>24;k[j+1|0]=(n<<4|(o>>>2|0))<<24>>24;}},BA=(b,c)=>{Bk();return b.data[c];},MK=(b,c,
d)=>{let e,f,g,h;Bk();e=b.data.length;f=((e+2|0)/3|0)*4|0;if(!d){g=e%3|0;if(g)f=f-(3-g|0)|0;}h=Bf(f);K6(b,h,c,d);return h;},K6=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q;Bk();f=b.data;g=f.length;h=(g/3|0)*3|0;i=0;j=0;while(j<h){k=c.data;l=i+1|0;k[i]=Bu(d,(f[j]>>>2|0)<<24>>24);m=l+1|0;n=f[j]<<4;o=j+1|0;k[l]=Bu(d,(n|((f[o]&255)>>>4|0))<<24>>24);n=m+1|0;p=f[o]<<2;o=o+1|0;k[m]=Bu(d,(p|((f[o]&255)>>>6|0))<<24>>24);i=n+1|0;k[n]=Bu(d,f[o]);j=o+1|0;}q=g-j|0;if(q==1){k=c.data;m=i+1|0;k[i]=Bu(d,(f[j]>>>2|0)<<24>>24);i=m
+1|0;k[m]=Bu(d,f[j]<<4<<24>>24);if(e){m=i+1|0;k[i]=61;i=m+1|0;k[m]=61;}}else if(q==2){k=c.data;n=i+1|0;k[i]=Bu(d,(f[j]>>>2|0)<<24>>24);o=n+1|0;p=f[j]<<4;m=j+1|0;k[n]=Bu(d,(p|((f[m]&255)>>>4|0))<<24>>24);n=o+1|0;k[o]=Bu(d,f[m]<<2<<24>>24);if(!e)i=n;else{i=n+1|0;k[n]=61;}}return i;},Bu=(b,c)=>{Bk();return b.data[c&63];},LX=()=>{let b,c,d,e;Bv=Bf(64);BT=Bf(64);CD=U(256);CV=U(256);b=0;c=65;while(c<=90){d=Bv.data;e=c<<24>>24;d[b]=e;BT.data[b]=e;b=b+1|0;c=(c+1|0)&65535;}c=97;while(c<=122){d=Bv.data;e=c<<24>>24;d[b]
=e;BT.data[b]=e;b=b+1|0;c=(c+1|0)&65535;}c=48;while(c<=57){d=Bv.data;e=c<<24>>24;d[b]=e;BT.data[b]=e;b=b+1|0;c=(c+1|0)&65535;}Bv.data[b]=43;BT.data[b]=45;e=b+1|0;Bv.data[e]=47;BT.data[e]=95;Go(CD,(-1));Go(CV,(-1));e=0;while(e<Bv.data.length){CD.data[Bv.data[e]]=e;CV.data[BT.data[e]]=e;e=e+1|0;}};
function HA(){let a=this;F.call(a);a.gj=null;a.gk=null;a.gM=0;a.f9=0;}
let Fr=(a,b,c)=>{J(a);a.gj=b;a.gk=c;},LI=(a,b)=>{let c=new HA();Fr(c,a,b);return c;},Lr=(a,b)=>{return O(a.gj)<b?0:1;},Lm=(a,b)=>{return O(a.gk)<b?0:1;},Kf=(a,b)=>{a.gM=b;},MG=(a,b)=>{a.f9=b;},Ne=G(),IV=(b,c)=>{let d,e,f,g,h,i,j,k;if(!b)return I(35);d=1<<c;e=d-1|0;f=(((32-KD(b)|0)+c|0)-1|0)/c|0;g=Bt(f);h=V(f-1|0,c);i=0;while(h>=0){j=g.data;k=i+1|0;j[i]=D1((b>>>h|0)&e,d);h=h-c|0;i=k;}return Ey(g);},Lg=G(),FU=b=>{return Math.log(b);},H9=b=>{return Math.ceil(b);},Nh=(b,c)=>{return IP(b,c);},IP=(b,c)=>{return Math.pow(b,
c);},Jy=()=>{return MO();},MO=()=>{return Math.random();},Bm=(b,c)=>{if(b<c)c=b;return c;},BQ=(b,c)=>{if(b>c)c=b;return c;},C3=G(B4),Hd=a=>{Ds(a);};
function Hf(){C3.call(this);this.gS=null;}
let HF=(a,b)=>{Hd(a);a.gS=b;},Is=a=>{let b=new Hf();HF(b,a);return b;},K9=a=>{return L_(a.gS);},MP=G();
function HS(){let a=this;Bs.call(a);a.g$=0;a.gZ=0;}
let Gj=(a,b,c,d)=>{Ce(a,b,Bd(Z,0));a.g$=c;a.gZ=d;},D0=(a,b,c)=>{let d=new HS();Gj(d,a,b,c);return d;},F6=G(0);
function CF(){F.call(this);this.fJ=null;}
let F7=a=>{J(a);a.fJ=Kt(107,14,12,5,3,64);},MS=()=>{let a=new CF();F7(a);return a;},JN=a=>{return a.fJ.dM();},KN=(a,b)=>{a.fJ.dN(b);},KU=(a,b)=>{return a.fJ.dO(b);},Md=(a,b)=>{return a.fJ.dP(b);},Lh=()=>{return MS();},LG=(b,c)=>{c=BG(c);return Cf(b.dP(c));},Ka=b=>{return Cf(b.dM());},Ld=(b,c)=>{c=BG(c);b.dN(c);},JB=(b,c)=>{c=BG(c);return Cf(b.dO(c));};
function Hv(){let a=this;F.call(a);a.gC=null;a.fh=null;a.fg=0;a.fs=null;}
let F_=(a,b,c)=>{let d;d=b.data;J(a);a.fg=d.length;a.gC=b;a.fh=D3([a.fg+1|0,a.fg]);F0(a);a.fs=c;},LY=(a,b)=>{let c=new Hv();F_(c,a,b);return c;},F0=a=>{let b;b=0;while(b<a.fg){a.fh.data[b]=BK(a.gC.data[b],a.fg+1|0);b=b+1|0;}},LW=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m;c=Eq(a);d=a.fs.fj;e=KG(a.fg);f=1;g=d;while(f<b){h=V(g,a.fs.fj);i=B0(h);F0(a);j=JR(a,c,i);k=0;while(k<a.fg){l=e.fe.data[k]-j.fe.data[k]|0;a.fh.data[k].data[a.fg]=a.fs.D(l/d|0);k=k+1|0;}m=Eq(a);c=c.dU(m.dV(d,i),i);f=f+1|0;g=h;d=h;}return c;},JR=(a,b,c)=>
{let d,e,f,g;d=U(a.fg);e=0;while(e<a.fg){f=0;while(f<a.fg){g=d.data;g[e]=c.D(g[e]+V(a.fh.data[e].data[f],b.fe.data[f])|0);f=f+1|0;}e=e+1|0;}return Bq(d);},Eq=a=>{let b,c,d,e,f,g,h,i,j;b=0;while(true){if(b>=a.fg){b=a.fg-1|0;while(b>=0){c=b-1|0;while(c>=0){a.dW(b,c,a.fs);c=c+(-1)|0;}b=b+(-1)|0;}d=U(a.fg);b=0;while(b<a.fg){e=d.data;f=a.fh.data[b].data[b];g=a.fh.data[b].data[a.fg];e[b]=a.fs.D(V(g,a.fs.dX(f)));b=b+1|0;}return Bq(d);}c=b;a:{while(true){if(c>=a.fg)break a;if(a.fh.data[c].data[b])break;c=c+1|0;}}if
(c==a.fg)break;h=a.fh.data[b];a.fh.data[b]=a.fh.data[c];a.fh.data[c]=h;a.dY(b,a.fs.dX(a.fh.data[b].data[b]),a.fs);i=b+1|0;j=i;while(j<a.fg){a.dW(b,j,a.fs);j=j+1|0;}b=i;}H(IL(I(36)));},LH=(a,b,c,d)=>{let e;e=0;while(e<(a.fg+1|0)){a.fh.data[b].data[e]=d.dq(V(a.fh.data[b].data[e],c));e=e+1|0;}},Iv=(a,b,c,d)=>{let e,f;e=a.fh.data[c].data[b];if(!e)return;f=0;while(f<(a.fg+1|0)){a.fh.data[c].data[f]=d.dq(a.fh.data[c].data[f]-V(a.fh.data[b].data[f],e)|0);f=f+1|0;}},Js=G(),EQ=b=>{return LE(b,I(37));},LE=(b,c)=>{if(b
!==null)return b;H(Hr(c));},Hy=(b,c,d)=>{if(b>=0&&c>=0&&c<=(d-b|0))return b;H(B$());},ML=G(),Ij=()=>{let b;b=new DM;Bk();EK(b,Bv,1);return b;},Mj=()=>{let b;b=new Dg;Bk();Eu(b,CD);return b;},Dh=G(),HT=a=>{J(a);},Mw=(a,b)=>{return LK(a,b);};
function H6(){Dh.call(this);this.gc=null;}
let FH=(a,b)=>{HT(a);a.gc=b;},Kr=a=>{let b=new H6();FH(b,a);return b;},Ma=(a,b)=>{let c;c=LL(b);while(a.gc.d3(c)){if(c.gN)continue;else return 1;}return 0;},Li=a=>{return Ev((a.gc.d4()));};
function CB(){let a=this;F.call(a);a.fZ=null;a.fG=null;}
let D6=(a,b,c)=>{J(a);a.fZ=b;a.fG=c;},NA=(a,b)=>{let c=new CB();D6(c,a,b);return c;},Ls=a=>{return a.fZ;},Ml=a=>{return a.fG;};
function C7(){let a=this;CB.call(a);a.f4=0;a.fx=null;}
let GR=(a,b,c)=>{D6(a,b,null);a.f4=c;},IO=(a,b)=>{let c=new C7();GR(c,a,b);return c;},Ew=G(0),Ht=G(Bs),Fh=a=>{Ce(a,I(38),Bd(Z,0));},L1=()=>{let a=new Ht();Fh(a);return a;},FV=G(N),E5=a=>{Y(a);},CP=()=>{let a=new FV();E5(a);return a;},FB=G(0);
function E4(){let a=this;F.call(a);a.f3=null;a.fV=null;}
let Fi=(a,b)=>{J(a);a.f3=b;},Ir=a=>{let b=new E4();Fi(b,a);return b;},ME=(a,b)=>{Kz(a);if(!a.fV.L())return 0;b.d7(a.fV.M());return 1;},Kz=a=>{if(a.fV===null)a.fV=a.f3.K();},Nk=a=>{return Bg(a.f3.N());};
function Dp(){let a=this;DX.call(a);a.gX=0;a.gt=0;}
let Gn=(a,b,c)=>{C9(a,0,b,Bf(b),0,b,c,0);},M2=(a,b)=>{let c=new Dp();Gn(c,a,b);return c;},C9=(a,b,c,d,e,f,g,h)=>{FR(a,b,c,d,e,f);a.gX=g;a.gt=h;},I_=(a,b,c,d,e,f,g)=>{let h=new Dp();C9(h,a,b,c,d,e,f,g);return h;},Ko=a=>{return a.gt;},F8=G(N),Fx=a=>{Y(a);},DT=()=>{let a=new F8();Fx(a);return a;},DV=G(),Eh=a=>{J(a);};
function CA(){let a=this;DV.call(a);a.fH=0;a.fi=null;a.fD=0;a.gT=0.0;a.f7=0;}
let Kj=(a,b)=>{return Bd(C7,b);},Ep=a=>{CU(a,16);},H1=()=>{let a=new CA();Ep(a);return a;},CU=(a,b)=>{DI(a,b,0.75);},NK=a=>{let b=new CA();CU(b,a);return b;},Gt=b=>{let c,d;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;d=c|c>>1;d=d|d>>2;d=d|d>>4;d=d|d>>8;d=d|d>>16;return d+1|0;},DI=(a,b,c)=>{let d;Eh(a);if(b>=0&&c>0.0){d=Gt(b);a.fH=0;a.fi=a.d_(d);a.gT=c;Hg(a);return;}H(BR());},NM=(a,b)=>{let c=new CA();DI(c,a,b);return c;},Hg=a=>{a.f7=a.fi.data.length*a.gT|0;},MM=a=>{return Is(a);},Ky=(a,b)=>{let c;c
=Hm(a,b);if(c===null)return null;return c.fG;},Hm=(a,b)=>{let c,d,e;if(b===null)c=D_(a);else{d=b.ed();e=d&(a.fi.data.length-1|0);c=C$(a,b,e,d);}return c;},C$=(a,b,c,d)=>{let e;e=a.fi.data[c];while(e!==null&&!(e.f4==d&&KA(b,e.fZ))){e=e.fx;}return e;},D_=a=>{let b;b=a.fi.data[0];while(b!==null&&b.fZ!==null){b=b.fx;}return b;},Jv=(a,b,c)=>{return J5(a,b,c);},J5=(a,b,c)=>{let d,e,f,g,h;if(b===null){d=D_(a);if(d===null){a.fD=a.fD+1|0;d=G$(a,null,0,0);e=a.fH+1|0;a.fH=e;if(e>a.f7)a.ei();}}else{f=b.ed();g=f&(a.fi.data.length
-1|0);d=C$(a,b,g,f);if(d===null){a.fD=a.fD+1|0;d=G$(a,b,g,f);e=a.fH+1|0;a.fH=e;if(e>a.f7)a.ei();}}h=d.fG;d.fG=c;return h;},G$=(a,b,c,d)=>{let e;e=IO(b,d);e.fx=a.fi.data[c];a.fi.data[c]=e;return e;},JT=(a,b)=>{let c,d,e,f,g,h,i;c=Gt(!b?1:b<<1);d=a.d_(c);e=0;while(e<a.fi.data.length){f=a.fi.data[e];a.fi.data[e]=null;while(f!==null){g=d.data;h=f.f4&(c-1|0);i=f.fx;f.fx=g[h];g[h]=f;f=i;}e=e+1|0;}a.fi=d;Hg(a);},MC=a=>{a.ek(a.fi.data.length);},KA=(b,c)=>{return b!==c&&!b.el(c)?0:1;},M1=G();
function Gm(){let a=this;F.call(a);a.fW=null;a.ha=null;a.fm=0;}
let Ge=(a,b)=>{let c,d;J(a);a.fm=b.fe.data.length;a.fW=D3([a.fm+1|0,a.fm]);a.ha=D3([a.fm+1|0,a.fm]);c=0;while(c<a.fm){d=0;while(d<a.fm){a.fW.data[c].data[d]=b.fe.data[FC((a.fm-d|0)+c|0,a.fm)];d=d+1|0;}c=c+1|0;}a.fW.data[0].data[a.fm]=1;},MY=a=>{let b=new Gm();Ge(b,a);return b;},Mk=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p;c=Mi(b);d=B0(b);e=U(a.fm);f=(c.en()).K();while(f.L()){g=f.M();h=(g.eo()).I();i=Nh(h,(g.eq()).er())|0;j=B0(h);k=(LY(a.fW,j)).et((g.eq()).er());l=b/i|0;m=B0(i);n=m.dX(l);o=0;while(o<a.fm){p=e.data;p[o]
=d.D(p[o]+V(V(k.fe.data[o],l),n)|0);o=o+1|0;}}return Bq(e);},Mi=b=>{let c,d,e;c=2;d=H1();e=b;while(c<=b&&e!=1){if(e%c|0){c=c+1|0;continue;}e=e/c|0;(d.F(BH(c),LA())).eu();}return d;},LT=b=>{return KZ();};
function C4(){let a=this;F.call(a);a.fB=0;a.fU=0;}
let Bb=null,Bc=null,R=()=>{R=X(C4);IF();},HN=(a,b,c)=>{R();J(a);a.fB=b;a.fU=c;},DG=(a,b)=>{let c=new C4();HN(c,a,b);return c;},Jn=a=>{return a.fB?0:1;},Kp=a=>{return a.fB!=1?0:1;},MN=a=>{return !a.bF()&&!a.bG()?0:1;},Kw=a=>{return a.fB!=2?0:1;},KJ=a=>{return a.fB!=3?0:1;},I9=a=>{if(a.bO())return a.fU;H(J6());},Bw=b=>{R();return DG(2,b);},Nl=a=>{switch(a.fB){case 0:H(Ja());case 1:H(Mh());case 2:H(Mf(a.fU));case 3:H(Jb(a.fU));default:}},IF=()=>{Bb=DG(0,0);Bc=DG(1,0);},LM=G(),IS=b=>{let copy=new b.constructor();for
(let field in b){if(b.hasOwnProperty(field)){copy[field]=b[field];}}return copy;},JS=(b,c)=>{return b!==null&&!(typeof b.constructor.$meta==='undefined'?1:0)&&FW(b.constructor,c)?1:0;},FW=(b,c)=>{let d,e;if(b===c)return 1;d=b.$meta.supertypes;e=0;while(e<d.length){if(FW(d[e],c))return 1;e=e+1|0;}return 0;},IN=b=>{return b.$meta.primitive?1:0;},LZ=b=>{return b.$meta.item;};
function HP(){let a=this;F.call(a);a.gr=null;a.gs=null;}
let EZ=(a,b,c)=>{J(a);a.gr=b;a.gs=c;},M0=(a,b)=>{let c=new HP();EZ(c,a,b);return c;},IH=(a,b)=>{return If(a.gr,a.gs,b);};
function H_(){let a=this;F.call(a);a.gQ=null;a.g_=null;a.gu=null;a.gv=null;a.gR=null;a.gm=null;a.fw=null;a.fo=null;a.fl=0;a.ga=0;a.fS=0;a.g5=null;a.g3=null;}
let E8=(a,b,c,d,e,f)=>{let g;J(a);a.gQ=b;a.g_=c;a.fw=B0(e);a.fo=B0(f);a.fl=c.fe.data.length;a.ga=d;a.fS=H9(a.fl*H9(FU(f)/FU(2.0))/8.0)|0;g=MY(b);a.gu=g.et(e);a.gv=g.et(f);a.gR=a.gv.eB(c,a.fo);},Lj=(a,b,c,d,e)=>{let f=new H_();E8(f,a,b,c,d,e);return f;},Kt=(b,c,d,e,f,g)=>{let h,i,$$je;h=0;while(true){if(h>=100)H(D7(I(39)));try{i=Lj(DU(b,c+1|0,c),DU(b,d,d),e,f,g);break;}catch($$e){$$je=BL($$e);if($$je instanceof Ci){}else{throw $$e;}}h=h+1|0;}return i;},KP=a=>{return a.eE(a.eF(a.gR));},Iz=(a,b)=>{let $$je;a:{try
{a.gm=a.eG(a.eH(b));}catch($$e){$$je=BL($$e);if($$je instanceof B_){break a;}else{throw $$e;}}return;}H(D7(I(40)));},Ll=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,$$je;Ck();c=Du(a,b.eJ(Dt),a.fw.fj,1);d=c.data;d=BK(c,d.length+1|0);e=d.data;f=e.length;e[f-1|0]=1;g=(f/a.fl|0)+(!(f%a.fl|0)?0:1)|0;h=U(V(g,a.fl));i=0;while(true){if(i>=f){d=h.data;a.g5=h;f=d.length;j=U(f+1|0);d=j.data;BP(h,0,j,1,f);d[0]=1;return a.eE(Dd(a,j,a.fo.fj,0,0,0));}k=Bm(f-i|0,a.fl);l=U(k);BP(d,i,l,0,k);try{m=MD(a,DN(l,a.fl,1));BP(m.fe,0,h,i,a.fl);}
catch($$e){$$je=BL($$e);if($$je instanceof B_){n=$$je;break;}else{throw $$e;}}i=i+a.fl|0;}H(H7(I(41),n));},LD=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,$$je;c=Du(a,a.eH(b),a.fo.fj,0);d=c.data;e=U(d.length-1|0);d=e.data;f=d.length;BP(c,1,e,0,f);a.g3=e;g=Cs();h=0;while(true){if(h>=f){i=((g.eN()).eO(Kn())).eP();j=new Z;d=Dd(a,i,a.fw.fj,1,0,1);Ck();Dc(j,d,Dt);return j;}k=Bm(f-h|0,a.fl);l=U(k);BP(e,h,l,0,k);try{m=(a.eR(DN(l,a.fl,0))).fe;d=m.data;n=d.length;o=0;while(o<n){p=d[o];g.J(BH(p));o=o+1|0;}}catch($$e){$$je
=BL($$e);if($$je instanceof B_){q=$$je;break;}else{throw $$e;}}h=h+a.fl|0;}H(H7(I(41),q));},MD=(a,b)=>{let c;c=DU(a.fl,a.ga,a.ga);return ((c.dV(a.fw.fj,a.fo)).eB(a.gm,a.fo)).dU(b,a.fo);},LO=(a,b)=>{return Dd(a,b.fe,a.fo.fj,0,1,0);},In=(a,b)=>{return (Ij()).eT(b);},M6=(a,b)=>{let c;c=(((a.gQ.eB(b,a.fo)).eU(a.fo)).eB(a.gu,a.fw)).eU(a.fw);return c.eV(a.fw);},MH=(a,b)=>{return DN(Du(a,b,a.fo.fj,0),a.fl,0);},Kc=(a,b)=>{return (Mj()).eX(b);},Du=(a,b,c,d)=>{let e,f,g,h,i;e=b.data;f=U(e.length);g=0;while(true){h=f.data;if
(g>=h.length)break;h[g]=e[g]&255;g=g+1|0;}i=a.eY(f,256,c,d,0);return i;},Dd=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m;g=a.eY(b,c,256,d,f);if(!e)h=g;else{i=g.data.length;if(i>=a.fS)h=g;else{h=U(a.fS);BP(g,0,h,a.fS-i|0,i);}}j=h.data;i=j.length;k=Bf(i);l=0;while(true){m=k.data;if(l>=m.length)break;m[l]=j[l]<<24>>24;l=l+1|0;}return F2(k,i);},L6=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p;g=b.data;h=g.length-1|0;a:{while(true){if(!e)break a;if(h<0)break a;if(g[h])break;h=h+(-1)|0;}}g=BK(b,(h+1|0)-(!f?0:1)|0);i=0;j=Cs();while
(true){k=0;l=1;m=i;n=i;i=m;while(true){o=g.data;if(n>=o.length)break;p=V(c,k)+o[n]|0;o[n]=p/d|0;k=p%d|0;if(l){if(o[n])l=0;else i=n;}n=n+1|0;}j.eZ(0,BH(k));if(l)break;}return ((j.eN()).eO(KX())).eP();};
function CM(){F.call(this);this.g0=null;}
let E9=null,Bo=null,BF=null,Bj=()=>{Bj=X(CM);IJ();},HH=(a,b)=>{Bj();J(a);a.g0=b;},DA=a=>{let b=new CM();HH(b,a);return b;},IJ=()=>{E9=DA(I(42));Bo=DA(I(43));BF=DA(I(44));},E$=G(N),GI=a=>{Y(a);},Ja=()=>{let a=new E$();GI(a);return a;},Bl=G(N),DH=a=>{Y(a);},BR=()=>{let a=new Bl();DH(a);return a;},BV=(a,b)=>{Cb(a,b);},BX=a=>{let b=new Bl();BV(b,a);return b;};
function H3(){Bl.call(this);this.g6=null;}
let Fk=(a,b)=>{DH(a);a.g6=b;},Da=a=>{let b=new H3();Fk(b,a);return b;},HV=G(N),E6=a=>{Y(a);},Il=()=>{let a=new HV();E6(a);return a;},Hi=G(),Fu=a=>{J(a);},KX=()=>{let a=new Hi();Fu(a);return a;},MR=(a,b)=>{return Hb(a,b);},Hb=(a,b)=>{return b.I();},EA=G(),DZ=0,B3=null,CJ=null,B2=()=>{B2=X(EA);I7();},Jh=(b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u;B2();d=JZ(b);c.gE=!(d&(-2147483648))?0:1;e=d&8388607;f=d>>23&255;if(!e&&!f){c.f5=0;c.ge=0;return;}if(f)g=e|8388608;else{g=e<<1;while(Im(CL(Bg(g),Bg(8388608)),Nd))
{g=g<<1;f=f+(-1)|0;}}h=JI(CJ,f);if(h<0)h= -h|0;i=CJ.data;j=h+1|0;k=f-i[j]|0;l=9+k|0;m=CI(g,B3.data[j],l);if(m<DZ){while(Br(m,DZ)<=0){h=h+(-1)|0;m=(m*10|0)+9|0;}i=CJ.data;j=h+1|0;n=f-i[j]|0;l=9+n|0;m=CI(g,B3.data[j],l);}j=g<<1;g=j+1|0;i=B3.data;n=h+1|0;o=i[n];p=l-1|0;q=CI(g,o,p);r=CI(j-1|0,B3.data[n],p);s=Kq(m,r);t=KY(m,q);u=Br(s,t);j=u>0?V(Be(m,s),s):u<0?V(Be(m,t),t)+t|0:V(Be((m+(t/2|0)|0),t),t);if(JY(Bg(j),Bg(1000000000))>=0)while(true){h=h+1|0;j=Be(j,10);if(Br(j,1000000000)<0)break;}else if(Br(j,100000000)
<0){h=h+(-1)|0;j=j*10|0;}c.f5=j;c.ge=h-50|0;},Kq=(b,c)=>{let d,e,f,g;B2();d=1;while(true){e=d*10|0;f=Be(b,e);g=Be(c,e);if(Br(f,g)<=0)break;d=e;}return d;},KY=(b,c)=>{let d,e,f,g;B2();d=1;while(true){e=d*10|0;f=Be(b,e);g=Be(c,e);if(Br(f,g)>=0)break;d=e;}return d;},CI=(b,c,d)=>{let e;B2();e=JA(CL(Bg(b),Df(4294967295, 0)),CL(Bg(c),Df(4294967295, 0)));return Ev(J1(e,32-d|0));},I7=()=>{DZ=Be((-1),10);B3=GA([(-18543760),(-873828468),(-1558056233),(-2105438446),(-791721136),(-1492370368),(-2052889754),(-707643228),
(-1425108042),(-1999079893),(-621547450),(-1356231419),(-1943978595),(-533385374),(-1285701758),(-1887554866),(-443107408),(-1213479385),(-1829776968),(-350662770),(-1139523676),(-1770612400),(-255999462),(-1063793029),(-1710027882),(-159064234),(-986244846),(-1647989336),(-59802560),(-906835507),(-1584461865),(-2126562952),(-825520345),(-1519409735),(-2074521247),(-742253618),(-1452796353),(-2021230542),(-656988489),(-1384584251),(-1966660860),(-569676998),(-1314735058),(-1910781505),(-480270031),(-1243209484),
(-1853561046),(-388717296),(-1169967296),(-1794967296),(-294967296),(-1094967296),(-1734967296),(-198967296),(-1018167296),(-1673527296),(-100663296),(-939524096),(-1610612736),(-2147483648),(-858993460),(-1546188227),(-2095944041),(-776530088),(-1480217529),(-2043167483),(-692087595),(-1412663535),(-1989124287),(-605618482),(-1343488245),(-1933784055),(-517074110),(-1272652747),(-1877115657),(-426404674),(-1200117198),(-1819087218),(-333559171),(-1125840796),(-1759666096),(-238485376),(-1049781760),(-1698818867),
(-141129810),(-971897307),(-1636511305),(-41437710),(-892143627),(-1572708361),(-2117160148),(-810475859),(-1507374147),(-2064892777),(-726848065),(-1440471911),(-2011370988),(-641213203),(-1371964022),(-1956564688)]);CJ=GA([(-37),(-34),(-31),(-28),(-24),(-21),(-18),(-14),(-11),(-8),(-4),(-1),2,6,9,12,16,19,22,26,29,32,36,39,42,46,49,52,56,59,62,65,69,72,75,79,82,85,89,92,95,99,102,105,109,112,115,119,122,125,129,132,135,139,142,145,149,152,155,158,162,165,168,172,175,178,182,185,188,192,195,198,202,205,208,
212,215,218,222,225,228,232,235,238,242,245,248,252,255,258,261,265,268,271,275,278,281,285,288,291]);};
function EW(){BJ.call(this);this.g4=0;}
let GK=(a,b)=>{CG(a);a.g4=b;},Jb=a=>{let b=new EW();GK(b,a);return b;},Fo=G(N),Gg=a=>{Y(a);},GD=()=>{let a=new Fo();Gg(a);return a;};
function Ee(){let a=this;F.call(a);a.f5=0;a.ge=0;a.gE=0;}
let El=a=>{J(a);},JW=()=>{let a=new Ee();El(a);return a;};
function Ft(){F.call(this);this.fF=null;}
let I8=(a,b)=>{let c;J(a);a.fF=b;c=a;b.classObject=c;},Mc=a=>{let b=new Ft();I8(b,a);return b;},Dk=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null)c=Mc(b);return c;},Gf=a=>{return a.fF;},Ej=(a,b)=>{return JS(b,a.fF);},B8=a=>{return IN(a.fF);},Cl=a=>{return Dk(LZ(a.fF));},G4=a=>{return 1;},GY=G(0),He=G(),EC=a=>{J(a);},La=()=>{let a=new He();EC(a);return a;},G7=G(CH),F9=(a,b)=>{CT(a,b);},L_=a=>{let b=new G7();F9(b,a);return b;},IY=a=>{GJ(a);return a.fC;},LU=a=>{return a.e_();};
Jo([]);
CZ([F,0,0,[],0,3,0,0,["n",D(Cu),"f",D(G2),"c",D(EE),"cn",D(MZ)],BB,0,F,[],0,3,0,0,["h",D(Jc),"fa",D(H4),"fb",D(Ia)],Ba,0,BB,[],0,3,0,0,["d",D(Cd),"i",L(Dj),"j",E(B5)],N,0,Ba,[],0,3,0,0,["d",D(Y),"i",L(Ha),"j",E(Cb)],T,0,N,[],0,3,0,0,["d",D(DQ),"j",E(W)],BO,0,F,[],3,3,0,0,0,BS,0,F,[BO],1,3,0,0,["d",D(GC)],Bz,0,F,[],3,3,0,0,0,GL,0,BS,[Bz],0,3,0,CO,0,KM,0,F,[],0,3,0,0,0,Cw,0,Ba,[],0,3,0,0,["d",D(Dn)],BJ,0,Cw,[],0,3,0,0,["d",D(CG)],HO,0,BJ,[],0,3,0,0,["y",E(F5)],Ln,0,F,[],4,3,0,0,0,FZ,0,F,[],0,3,0,0,["c3",L(Fj),
"c8",D(ID),"c6",E(II),"c$",E(JC),"c_",E(Ng)],B6,0,BS,[Bz],0,3,0,BM,["y",E(Eg),"I",D(Kh),"ed",D(IG),"el",E(Me)],Er,0,Ba,[],0,3,0,0,["d",D(GM)],Gl,0,F,[],0,0,0,Ea,0,DO,0,F,[Bz],0,3,0,Bp,0,HB,0,F,[],0,3,0,0,["y",E(G6),"D",E(Mo),"dq",E(Jf),"dX",E(MW)],HM,0,BS,[Bz],0,3,0,EP,0,EV,0,F,[],3,3,0,0,["F",L(CX)],DP,0,F,[],3,3,0,0,0,Hs,0,F,[DP],0,3,0,0,["H",E(Gr),"Q",E(Jl),"S",E(FL)],CQ,0,F,[],3,3,0,0,0,HL,0,F,[CQ],0,0,0,0,["V",E(Fb),"bY",E(J2)],Ho,0,F,[],3,3,0,0,0,Dl,0,F,[Ho],3,3,0,0,0,HI,0,F,[Dl],3,3,0,0,0,Dx,0,F,[HI],
1,3,0,0,["d",D(Gi),"eP",D(Mg)],Gz,0,N,[],0,3,0,0,["d",D(Fz)],D2,0,F,[],3,3,0,0,0,Ef,0,F,[D2],0,3,0,0,["d",D(HY),"bZ",E(Iq),"ba",E(FP)],Cv,0,F,[],3,3,0,0,0,B7,0,F,[],1,3,0,0,["y",E(C5),"cL",D(CW),"bD",D(Bi),"bo",E(De),"cK",D(C_),"bn",D(DY),"v",D(O),"u",D(Bh)],Dr,0,F,[],3,3,0,0,0,H2,0,F,[],3,3,0,0,0,C8,0,B7,[Bz,Dr,Cv,H2],1,3,0,0,["bp",S(EB),"bf",S(J4),"cM",E(Mn),"dx",S(M4),"bk",S(KT),"bE",E(Cm),"cJ",D(GX),"bS",D(DS),"bR",D(E0),"bV",E(Ii)],CR,0,C8,[],1,0,0,0,["bp",S(HG),"bg",D(Mt)],DE,0,CR,[],0,0,0,0,["y",E(Gy),
"bc",function(b,c,d,e,f,g){Eb(this,b,c,d,e,f,g);},"be",E(KF),"bh",L(Ig),"bl",D(Ku),"bm",D(JD),"bq",D(L2)],Fd,0,F,[],3,3,0,0,0,Ct,0,F,[Fd],3,3,0,0,["bt",D(By),"eN",D(BC)],Hn,0,F,[Ct],3,3,0,0,["bt",D(By),"eN",D(BC)],G0,0,T,[],0,3,0,0,["d",D(E_)],Dq,0,F,[],1,3,0,0,["c2",S(HK),"cq",E(FE),"bv",E(Kl),"cr",E(FI),"bw",E(KL),"bM",S(C6),"bQ",E(Hj),"bK",D(Ga),"cs",E(Hc),"bH",E(Jp),"bI",D(IB)],Em,0,Dx,[],0,3,0,0,["d1",L(HW),"W",E(Mp),"U",D(Ki)],FS,0,F,[],4,3,0,Ck,0,Dy,0,F,[],4,3,0,Cy,0,FO,0,F,[Dl],3,3,0,0,0,B9,0,F,[BO,
Cv],0,0,0,0,["d",D(DD),"y",E(Db),"cc",E(GE),"ca",L(Ei),"cd",E(Gs),"b4",L(J3),"b5",S(Lz),"ce",E(EG),"b8",L(Fy),"cf",E(Hh),"b_",L(GU),"b1",L(ES),"b3",E(Gh),"f",D(E7)]]);
CZ([EJ,0,B9,[Dr],0,3,0,0,["d",D(G1),"e",E(K),"E",E(M),"bu",E(Do),"bb",E(BN),"ci",L(I$),"cg",L(Ms),"ch",L(Kg),"cj",L(MF),"f",D(P),"b3",E(MU),"b1",L(I6),"b_",L(It),"b8",L(KE),"ca",L(M7)],Eo,0,F,[],0,3,0,En,0,Fv,0,N,[],0,3,0,0,["d",D(Hw)],Fc,0,F,[],3,3,0,0,0,G9,0,F,[],3,3,0,0,0,Dg,0,F,[],0,3,0,0,["cl",E(JV),"eX",E(IT)],Bs,0,F,[Bz],1,3,0,0,["cx",L(Ce),"cs",E(EM),"cw",E(GQ)],EI,0,Bs,[],0,3,0,0,["d",D(HC)],BI,0,BB,[],0,3,0,0,["d",D(DW),"i",L(DK),"by",E(Dz)],Ci,0,Ba,[],0,3,0,0,["j",E(Cj)],DC,0,BI,[],0,3,0,0,["d",D(FJ),
"i",L(Ib)],L3,0,N,[],0,3,0,0,0,B4,0,F,[Ct],1,3,0,0,["bt",D(By),"eN",D(BC),"d",D(Ds)],Hu,0,F,[Ct],3,3,0,0,["bt",D(By),"eN",D(BC)],EU,0,F,[Hu],3,3,0,0,["bt",D(By),"eN",D(BC)],DB,0,B4,[EU],1,3,0,0,["bt",D(By),"eN",D(BC),"d",D(GN),"K",D(IZ)],Cg,0,F,[],3,3,0,0,0,Gv,0,F,[],3,3,0,0,0,Dw,0,DB,[Cg,BO,Gv],0,3,0,0,["bt",D(By),"eN",D(BC),"d",D(Fn),"y",E(C1),"b3",E(JM),"Z",E(MT),"N",D(K1),"J",E(KW),"eZ",L(LQ)],Gc,0,BI,[],0,3,0,0,["by",E(EX)],FM,0,F,[DP],0,3,0,0,["d",D(Hq),"Q",E(K_),"cC",E(H8)],Cq,0,F,[G9,BO],0,3,0,0,["d",
D(C2),"dl",E(Ks),"cE",D(I3)],D$,0,Cq,[],0,3,0,CE,0,Z,0,F,[BO,Bz,Cv],0,3,0,BU,["d",D(E1),"dc",E(Fm),"fc",E(FG),"cb",S(H$),"eQ",L(Dc),"bj",E(KI),"bi",D(JG),"b2",D(L8),"f",D(LN),"eJ",E(Ke)],Id,0,N,[],0,3,0,0,["d",D(Gk)],CK,0,F,[],1,3,0,0,["cQ",JL(Gx),"c2",S(FF),"cu",E(Ed),"bv",E(L9),"cv",E(Gq),"bw",E(Lx),"cV",S(Dv),"cw",E(Ex),"cX",E(ET),"c1",E(IK),"cU",D(EL),"bI",D(KQ)],Ec,0,CK,[],1,3,0,0,["c2",S(Hp),"cR",L(KR)],H5,0,Ec,[],0,3,0,0,["dd",E(EF),"c4",function(b,c,d,e,f,g,h){return MQ(this,b,c,d,e,f,g,h);}],Cr,0,N,
[],0,3,0,0,["d",D(CY)],Ek,0,F,[],3,3,0,0,0,G5,0,F,[CQ],0,3,0,0,["Y",E(HX),"bY",E(Lk)],DM,0,F,[],0,3,0,0,["db",E(Ih),"eT",E(JU)],FA,0,F,[],0,0,0,0,["d",D(GV),"eu",D(My),"er",D(Lf)],B_,0,Ba,[],0,3,0,0,["j",E(Es)],D5,0,Bs,[],0,3,0,Cp,["cp",D(Ip),"ct",D(Ly)],D9,0,F,[],3,3,0,0,0,FN,0,F,[D9],0,0,0,0,["cy",E(Gw),"L",D(Jr),"M",D(J0)],Hx,0,Cr,[],0,3,0,0,["d",D(G8)],Fl,0,N,[],0,3,0,0,["d",D(EH)],Jz,0,F,[],4,3,0,0,0,EN,0,F,[],3,3,0,0,0,GH,0,F,[EN],0,0,0,0,["d2",E(Gu),"d7",E(J$)],CH,0,F,[],0,0,0,0,["dK",E(CT),"L",D(Jx),
"di",D(Ic),"e$",D(GJ)],Gp,0,F,[],0,3,0,0,["d",D(GP)],Ca,0,F,[],0,3,0,BD,["V",E(F1),"eM",S(F3),"dn",D(Ji),"dU",L(Iw),"eB",L(JX),"dV",L(Nf),"eU",E(Mz),"eV",E(MB)],C0,0,N,[],0,3,0,0,["j",E(ER),"d",D(Hk)],DX,0,B7,[Bz],1,3,0,0,["d8",function(b,c,d,e,f){FR(this,b,c,d,e,f);},"du",S(M3),"cO",E(KV),"c5",S(KO),"cS",E(Fp),"cJ",D(K5),"cN",D(DL),"cY",D(Fq),"bC",E(Jg)],DF,0,Dq,[],1,3,0,0,["c2",S(Gd),"bx",L(J8)],FD,0,DF,[],0,3,0,0,["dd",E(HE),"dw",function(b,c,d,e,f,g,h){return Lv(this,b,c,d,e,f,g,h);}],GS,0,F,[],4,3,0,Bk,
0]);
CZ([HA,0,F,[],0,3,0,0,["dv",L(Fr),"dy",E(Lr),"c6",E(Lm),"c$",E(Kf),"c_",E(MG)],Ne,0,F,[],4,3,0,0,0,Lg,0,F,[],4,3,0,0,0,C3,0,B4,[Hn],1,3,0,0,["bt",D(By),"eN",D(BC),"d",D(Hd)],Hf,0,C3,[],0,0,0,0,["bt",D(By),"eN",D(BC),"dK",E(HF),"K",D(K9)],MP,0,F,[],4,3,0,0,0,HS,0,Bs,[],0,3,0,0,["b0",S(Gj)],F6,0,F,[],3,3,0,0,0,CF,0,F,[],0,3,0,0,["d",D(F7),"dM",D(JN),"dN",E(KN),"dO",E(KU),"dP",E(Md)],Hv,0,F,[],0,0,0,0,["es",L(F_),"et",E(LW),"dY",S(LH),"dW",S(Iv)],Js,0,F,[],4,3,0,0,0,ML,0,F,[],4,3,0,0,0,Dh,0,F,[FO],1,3,0,0,["d",
D(HT),"eO",E(Mw)],H6,0,Dh,[],0,3,0,0,["bs",E(FH),"bW",E(Ma),"U",D(Li)],CB,0,F,[Ek,Cg],0,0,0,0,["d5",L(D6),"eo",D(Ls),"eq",D(Ml)],C7,0,CB,[],0,0,0,0,["ej",L(GR)],Ew,0,F,[],3,3,0,0,0,Ht,0,Bs,[],0,3,0,0,["d",D(Fh)],FV,0,N,[],0,3,0,0,["d",D(E5)],FB,0,F,[],3,3,0,0,0,E4,0,F,[FB],0,3,0,0,["br",E(Fi),"d3",E(ME),"d4",D(Nk)],Dp,0,DX,[],0,0,0,0,["ds",L(Gn),"dt",function(b,c,d,e,f,g,h){C9(this,b,c,d,e,f,g,h);},"bg",D(Ko)],F8,0,N,[],0,3,0,0,["d",D(Fx)],DV,0,F,[EV],1,3,0,0,["F",L(CX),"d",D(Eh)],CA,0,DV,[Cg,BO],0,3,0,0,["F",
L(CX),"d_",E(Kj),"d",D(Ep),"y",E(CU),"d9",L(DI),"en",D(MM),"P",E(Ky),"eb",E(Hm),"ee",S(C$),"ec",D(D_),"R",L(Jv),"ek",E(JT),"ei",D(MC)],M1,0,F,[],4,3,0,0,0,Gm,0,F,[],0,3,0,0,["eA",E(Ge),"et",E(Mk)],C4,0,F,[],0,3,0,R,["ev",L(HN),"bA",D(Jn),"bz",D(Kp),"bO",D(MN),"bF",D(Kw),"bG",D(KJ),"bi",D(I9),"bP",D(Nl)],LM,0,F,[],4,3,0,0,0,HP,0,F,[F6],0,3,0,0,["bX",L(EZ),"dh",E(IH)],H_,0,F,[],0,3,0,0,["eC",function(b,c,d,e,f){E8(this,b,c,d,e,f);},"dM",D(KP),"dN",E(Iz),"dO",E(Ll),"dP",E(LD),"eF",E(LO),"eE",E(In),"eR",E(M6),"eG",
E(MH),"eH",E(Kc),"eY",function(b,c,d,e,f){return L6(this,b,c,d,e,f);}],CM,0,F,[],0,3,0,Bj,["j",E(HH)],E$,0,N,[],0,3,0,0,["d",D(GI)],Bl,0,N,[],0,3,0,0,["d",D(DH),"j",E(BV)],H3,0,Bl,[],0,3,0,0,["j",E(Fk)],HV,0,N,[],0,3,0,0,["d",D(E6)],Hi,0,F,[D2],0,3,0,0,["d",D(Fu),"bZ",E(MR),"ba",E(Hb)],EA,0,F,[],4,3,0,B2,0,EW,0,BJ,[],0,3,0,0,["y",E(GK)],Fo,0,N,[],0,3,0,0,["d",D(Gg)],Ee,0,F,[],0,3,0,0,["d",D(El)],Ft,0,F,[Fc,Ew],4,3,0,0,["dg",D(Gf),"s",E(Ej),"r",D(B8),"m",D(Cl),"dr",D(G4)],GY,0,F,[],3,3,0,0,0,He,0,F,[GY],0,3,
0,0,["d",D(EC)],G7,0,CH,[D9],0,0,0,0,["dK",E(F9),"e_",D(IY),"M",D(LU)]]);
let GW=Bx(Gb),LF=Bx(Ie),G3=Bx(Cn),Fe=Bx(EY);
I0(["<java_object>@","Either src or dest is null","0 has no inverse mod "," has no inverse mod ","New position "," is outside of range [0;","Capacity is negative: ","The last char in dst "," is outside of array of size ","Length "," must be non-negative","Offset ","The last char in src "," is outside of string of size ","Start "," must be before end ","�","averageCharsPerByte must be positive. Actual value is ","maxCharsPerByte must be positive. Actual value is ","newAction must be non-null","UTF-16","UTF-16BE",
"UTF-16LE","BIG_ENDIAN","LITTLE_ENDIAN","null","Should never been thrown","ISO-8859-1","Replacement preconditions do not hold","Action must be non-null","UTF-8","message too long","d1 + d2 must not be greater than N","The last byte in dst ","The last byte in src ","0","no inverse exists in R","","US-ASCII","damn","could not decode foreign key","This should be impossible","IGNORE","REPLACE","REPORT"]);
Z.prototype.toString=function(){return Cf(this);};
Z.prototype.valueOf=Z.prototype.toString;F.prototype.toString=function(){return Cf(G2(this));};
F.prototype.__teavm_class__=function(){return M8(this);};
let NC=Symbol('jsoClass');
(()=>{let c;c=CF.prototype;c.setForeignKey=Cz(Ld);c.encrypt=Cz(JB);c.getPublicKey=Cz(Ka);c.decrypt=Cz(LG);})();
function C(){return Lh();};C.prototype=CF.prototype;export{C as NTRU};